import Foundation

/// Per-language data for Walter's daily story, bundled as
/// `Resources/story_lexicon_<code>.json` and generated by
/// `tools/build_story_lexicon.py` from the seed + frequency lists.
///
/// - `frequency`: seed lemmas, most frequent first (rank = index + 1). Used to
///   weight coverage stats and to pick which known words a story may use.
/// - `functionWords`: closed-class words a story may always use.
/// - `aliases`: extra lemma candidates for a surface form or for a lemma
///   NLTagger gets wrong (puede → "podar" → poder). Aliases only add
///   candidates, never remove them.
/// - `inflectionSuffixes`, `verbEndings`, `stemAlternations`,
///   `stemFinalAlternations`, `cliticSuffixes`, `separablePrefixes`,
///   `compoundLinkers`: morphology hints for `StoryVocabularyChecker`, which
///   lean on them when NLTagger has no lemma model for the language.
nonisolated struct StoryLexicon: Decodable, Sendable {
    let version: Int
    let language: String
    let frequency: [String]
    let functionWords: [String]
    let aliases: [String: [String]]
    let inflectionSuffixes: [[String]]
    let verbEndings: [String: [String]]?
    let stemAlternations: [[String]]?
    let stemFinalAlternations: [[String]]?
    let cliticSuffixes: [String]?
    let separablePrefixes: [String]?
    let compoundLinkers: [String]?

    static func resourceName(languageCode: String) -> String {
        "story_lexicon_\(languageCode)"
    }

    /// Loads the bundled lexicon for an ISO 639-1 code ("es", "fr", "de", "it").
    static func load(languageCode: String, bundle: Bundle = .main) -> StoryLexicon? {
        guard let url = bundle.url(forResource: resourceName(languageCode: languageCode), withExtension: "json"),
              let data = try? Data(contentsOf: url) else {
            print("[StoryLexicon] missing resource for \(languageCode)")
            return nil
        }
        do {
            return try JSONDecoder().decode(StoryLexicon.self, from: data)
        } catch {
            print("[StoryLexicon] failed to decode \(languageCode): \(error)")
            return nil
        }
    }

    /// 1-based frequency rank keyed by lemma exactly as it appears in the seed.
    func frequencyRanks() -> [String: Int] {
        var ranks: [String: Int] = [:]
        ranks.reserveCapacity(frequency.count)
        for (index, lemma) in frequency.enumerated() where ranks[lemma] == nil {
            ranks[lemma] = index + 1
        }
        return ranks
    }
}

extension StoryLexicon {
    static func load(for language: TargetLanguage, bundle: Bundle = .main) -> StoryLexicon? {
        load(languageCode: language.languageCode, bundle: bundle)
    }
}
