#!/usr/bin/env python3
"""Generate french_top1000.json — native-frequency-ordered starter set.

Build-time tool, NOT bundled in the app. Run:
    python3 tools/build_french.py

Frequency ordering is inspired by hermitdave/FrequencyWords (MIT) +
Lonsdale & Le Bras "A Frequency Dictionary of French". Example sentences
and English glosses authored from scratch.
"""

from vocab_pipeline import build_dataset


# (lemma, part_of_speech, english_gloss, french_example, english_translation)
ENTRIES: list[tuple[str, str, str, str, str]] = [
    # Essential verbs
    ("être", "verb", "to be", "Je suis étudiant.", "I am a student."),
    ("avoir", "verb", "to have", "J'ai faim.", "I'm hungry."),
    ("faire", "verb", "to do, to make", "Qu'est-ce que tu fais ?", "What are you doing?"),
    ("dire", "verb", "to say, to tell", "Dis-moi la vérité.", "Tell me the truth."),
    ("aller", "verb", "to go", "Je vais au marché.", "I'm going to the market."),
    ("voir", "verb", "to see", "Je veux voir le film.", "I want to see the film."),
    ("savoir", "verb", "to know (a fact)", "Je ne sais pas.", "I don't know."),
    ("pouvoir", "verb", "to be able, can", "Je ne peux pas y aller.", "I can't go."),
    ("vouloir", "verb", "to want", "Je veux un café.", "I want a coffee."),
    ("venir", "verb", "to come", "Viens ici.", "Come here."),
    ("prendre", "verb", "to take", "Je prends le bus.", "I take the bus."),
    ("trouver", "verb", "to find", "Je ne trouve pas mes clés.", "I can't find my keys."),
    ("donner", "verb", "to give", "Donne-moi la main.", "Give me your hand."),
    ("falloir", "verb", "to be necessary", "Il faut partir.", "We need to leave."),
    ("parler", "verb", "to speak, to talk", "Je parle deux langues.", "I speak two languages."),
    ("aimer", "verb", "to like, to love", "J'aime le café.", "I like coffee."),
    ("passer", "verb", "to pass, to spend (time)", "Passe une bonne journée.", "Have a good day."),
    ("mettre", "verb", "to put, to place", "Mets le livre sur la table.", "Put the book on the table."),
    ("devoir", "verb", "must, to owe", "Je dois travailler.", "I have to work."),
    ("comprendre", "verb", "to understand", "Je ne comprends pas.", "I don't understand."),
    ("attendre", "verb", "to wait", "Attends-moi.", "Wait for me."),
    ("sortir", "verb", "to go out, to leave", "Je sors ce soir.", "I'm going out tonight."),
    ("vivre", "verb", "to live", "Je vis à Paris.", "I live in Paris."),
    ("tenir", "verb", "to hold", "Tiens, c'est pour toi.", "Here, this is for you."),
    ("sembler", "verb", "to seem", "Ça semble facile.", "It seems easy."),
    ("laisser", "verb", "to leave, to let", "Laisse-moi tranquille.", "Leave me alone."),
    ("rester", "verb", "to stay", "Je reste à la maison.", "I'm staying home."),
    ("penser", "verb", "to think", "À quoi penses-tu ?", "What are you thinking about?"),
    ("suivre", "verb", "to follow", "Suis-moi.", "Follow me."),
    ("connaître", "verb", "to know (a person/place)", "Je connais ta sœur.", "I know your sister."),
    ("jouer", "verb", "to play", "Les enfants jouent dans le parc.", "The children play in the park."),
    ("écouter", "verb", "to listen", "J'écoute de la musique.", "I'm listening to music."),
    ("regarder", "verb", "to look at, to watch", "Regarde le ciel.", "Look at the sky."),
    ("entendre", "verb", "to hear", "Tu m'entends ?", "Can you hear me?"),
    ("sentir", "verb", "to feel, to smell", "Je me sens bien.", "I feel good."),
    ("partir", "verb", "to leave", "Je pars demain.", "I leave tomorrow."),
    ("arriver", "verb", "to arrive, to happen", "Le train arrive à huit heures.", "The train arrives at eight."),
    ("revenir", "verb", "to come back", "Je reviens dans une heure.", "I'll be back in an hour."),
    ("demander", "verb", "to ask", "Je te demande de m'aider.", "I'm asking you to help me."),
    ("répondre", "verb", "to answer", "Réponds à ma question.", "Answer my question."),
    ("chercher", "verb", "to look for", "Je cherche mon téléphone.", "I'm looking for my phone."),
    ("payer", "verb", "to pay", "Je paie par carte.", "I'll pay by card."),
    ("acheter", "verb", "to buy", "J'achète du pain.", "I'm buying bread."),
    ("vendre", "verb", "to sell", "Ils vendent des fruits.", "They sell fruit."),
    ("ouvrir", "verb", "to open", "Ouvre la fenêtre.", "Open the window."),
    ("fermer", "verb", "to close", "Ferme la porte.", "Close the door."),
    ("commencer", "verb", "to begin", "Le cours commence maintenant.", "The class starts now."),
    ("finir", "verb", "to finish", "Je finis le travail.", "I'll finish the work."),
    ("manger", "verb", "to eat", "On va manger.", "Let's eat."),
    ("boire", "verb", "to drink", "Je bois de l'eau.", "I drink water."),
    ("dormir", "verb", "to sleep", "Je dors huit heures.", "I sleep eight hours."),
    ("lire", "verb", "to read", "Je lis chaque soir.", "I read every evening."),
    ("écrire", "verb", "to write", "J'écris une lettre.", "I'm writing a letter."),
    ("apprendre", "verb", "to learn", "Je veux apprendre le français.", "I want to learn French."),
    ("étudier", "verb", "to study", "J'étudie pour l'examen.", "I'm studying for the exam."),
    ("travailler", "verb", "to work", "Je travaille au bureau.", "I work at the office."),
    ("marcher", "verb", "to walk, to work (function)", "On marche sur la plage.", "We walk on the beach."),
    ("courir", "verb", "to run", "Je cours chaque matin.", "I run every morning."),
    ("voyager", "verb", "to travel", "J'aime voyager.", "I like to travel."),
    ("conduire", "verb", "to drive", "Je conduis au travail.", "I drive to work."),
    ("gagner", "verb", "to win, to earn", "On a gagné le match.", "We won the game."),
    ("perdre", "verb", "to lose", "J'ai perdu mes clés.", "I lost my keys."),
    ("oublier", "verb", "to forget", "J'ai oublié son nom.", "I forgot his name."),
    ("appeler", "verb", "to call", "Je m'appelle Marie.", "My name is Marie."),
    ("rappeler", "verb", "to remember, to call back", "Je me rappelle ce jour.", "I remember that day."),
    ("choisir", "verb", "to choose", "Choisis une couleur.", "Choose a colour."),
    ("montrer", "verb", "to show", "Montre-moi la photo.", "Show me the photo."),
    ("expliquer", "verb", "to explain", "Explique-moi le problème.", "Explain the problem to me."),
    ("raconter", "verb", "to tell (a story)", "Raconte-moi une histoire.", "Tell me a story."),
    ("aider", "verb", "to help", "Tu peux m'aider ?", "Can you help me?"),
    ("chanter", "verb", "to sing", "Nous chantons à la fête.", "We sing at the party."),
    ("danser", "verb", "to dance", "Je danse le samedi.", "I dance on Saturdays."),
    ("cuisiner", "verb", "to cook", "Mon père cuisine bien.", "My father cooks well."),
    ("changer", "verb", "to change", "Je veux changer de travail.", "I want to change jobs."),
    ("utiliser", "verb", "to use", "J'utilise mon téléphone.", "I use my phone."),
    ("essayer", "verb", "to try", "Essaie encore une fois.", "Try again."),
    ("croire", "verb", "to believe", "Je crois que oui.", "I think so."),
    ("rencontrer", "verb", "to meet", "On se rencontre demain.", "We're meeting tomorrow."),

    # People / family nouns
    ("homme", "noun (masc.)", "man", "Cet homme est grand.", "That man is tall."),
    ("femme", "noun (fem.)", "woman, wife", "Cette femme est ma tante.", "That woman is my aunt."),
    ("enfant", "noun (masc./fem.)", "child", "L'enfant joue dehors.", "The child plays outside."),
    ("fils", "noun (masc.)", "son", "Mon fils a cinq ans.", "My son is five years old."),
    ("fille", "noun (fem.)", "girl, daughter", "Ma fille joue de la guitare.", "My daughter plays guitar."),
    ("père", "noun (masc.)", "father", "Mon père est médecin.", "My father is a doctor."),
    ("mère", "noun (fem.)", "mother", "Ma mère cuisine bien.", "My mother cooks well."),
    ("frère", "noun (masc.)", "brother", "Mon frère habite à Lyon.", "My brother lives in Lyon."),
    ("sœur", "noun (fem.)", "sister", "Ma sœur est professeure.", "My sister is a teacher."),
    ("ami", "noun (masc.)", "friend (male)", "Mon meilleur ami s'appelle Paul.", "My best friend's name is Paul."),
    ("amie", "noun (fem.)", "friend (female)", "Mon amie arrive ce soir.", "My friend arrives tonight."),
    ("famille", "noun (fem.)", "family", "Ma famille est grande.", "My family is big."),
    ("gens", "noun (masc. pl.)", "people", "Il y a beaucoup de gens ici.", "There are a lot of people here."),
    ("personne", "noun (fem.)", "person", "C'est une bonne personne.", "He is a good person."),

    # Time nouns
    ("jour", "noun (masc.)", "day", "Bonne journée.", "Have a good day."),
    ("nuit", "noun (fem.)", "night", "Bonne nuit.", "Good night."),
    ("matin", "noun (masc.)", "morning", "Bon matin.", "Good morning."),
    ("soir", "noun (masc.)", "evening", "Bonsoir.", "Good evening."),
    ("semaine", "noun (fem.)", "week", "À la semaine prochaine.", "See you next week."),
    ("mois", "noun (masc.)", "month", "Ce mois est mai.", "This month is May."),
    ("année", "noun (fem.)", "year", "Bonne année.", "Happy new year."),
    ("an", "noun (masc.)", "year (age)", "J'ai vingt ans.", "I am twenty years old."),
    ("heure", "noun (fem.)", "hour, time", "Quelle heure est-il ?", "What time is it?"),
    ("minute", "noun (fem.)", "minute", "Attends une minute.", "Wait a minute."),
    ("moment", "noun (masc.)", "moment", "Un moment, s'il vous plaît.", "One moment, please."),
    ("temps", "noun (masc.)", "time; weather", "Je n'ai pas le temps.", "I don't have time."),
    ("fois", "noun (fem.)", "time, occasion", "Pour la première fois.", "For the first time."),

    # Place nouns
    ("maison", "noun (fem.)", "house, home", "Je rentre à la maison.", "I'm going home."),
    ("rue", "noun (fem.)", "street", "J'habite dans cette rue.", "I live on this street."),
    ("ville", "noun (fem.)", "city, town", "Paris est une grande ville.", "Paris is a big city."),
    ("pays", "noun (masc.)", "country", "Je visite un autre pays.", "I'm visiting another country."),
    ("monde", "noun (masc.)", "world", "C'est le meilleur du monde.", "He's the best in the world."),
    ("lieu", "noun (masc.)", "place", "Ce lieu est joli.", "This place is nice."),
    ("place", "noun (fem.)", "square, place, seat", "Sur la place du village.", "On the village square."),
    ("école", "noun (fem.)", "school", "Je vais à l'école.", "I'm going to school."),
    ("travail", "noun (masc.)", "work, job", "Mon travail est difficile.", "My job is hard."),
    ("bureau", "noun (masc.)", "office, desk", "Le bureau est fermé.", "The office is closed."),

    # Common nouns
    ("chose", "noun (fem.)", "thing", "C'est une autre chose.", "That's a different thing."),
    ("vie", "noun (fem.)", "life", "La vie est belle.", "Life is beautiful."),
    ("main", "noun (fem.)", "hand", "Donne-moi la main.", "Give me your hand."),
    ("œil", "noun (masc.)", "eye", "Il a les yeux bleus.", "He has blue eyes."),
    ("voiture", "noun (fem.)", "car", "Ma voiture est rouge.", "My car is red."),
    ("eau", "noun (fem.)", "water", "Un verre d'eau, s'il vous plaît.", "A glass of water, please."),
    ("pain", "noun (masc.)", "bread", "J'achète du pain.", "I'm buying bread."),
    ("café", "noun (masc.)", "coffee, café", "Un café, s'il vous plaît.", "A coffee, please."),

    # Adjectives
    ("bon", "adjective", "good", "C'est très bon.", "It's very good."),
    ("mauvais", "adjective", "bad", "C'est un mauvais signe.", "It's a bad sign."),
    ("grand", "adjective", "big, tall", "C'est un grand homme.", "He is a tall man."),
    ("petit", "adjective", "small, little", "Une petite chambre.", "A small room."),
    ("beau", "adjective", "beautiful, handsome", "Quel beau jardin.", "What a beautiful garden."),
    ("joli", "adjective", "pretty", "C'est une jolie robe.", "It's a pretty dress."),
    ("jeune", "adjective", "young", "Elle est très jeune.", "She is very young."),
    ("vieux", "adjective", "old", "C'est un vieux livre.", "It's an old book."),
    ("nouveau", "adjective", "new", "J'ai un nouveau travail.", "I have a new job."),
    ("premier", "adjective", "first", "C'est sa première fois.", "It's his first time."),
    ("dernier", "adjective", "last", "La dernière chance.", "The last chance."),
    ("autre", "adjective", "other", "Un autre jour.", "Another day."),
    ("même", "adjective", "same", "Le même problème.", "The same problem."),
    ("important", "adjective", "important", "C'est important pour moi.", "It's important to me."),
    ("possible", "adjective", "possible", "Ce n'est pas possible.", "It's not possible."),
    ("facile", "adjective", "easy", "C'est facile.", "It's easy."),
    ("difficile", "adjective", "difficult", "C'est difficile à comprendre.", "It's hard to understand."),
    ("heureux", "adjective", "happy", "Je suis heureux.", "I am happy."),
    ("triste", "adjective", "sad", "Pourquoi es-tu triste ?", "Why are you sad?"),
    ("content", "adjective", "pleased, happy", "Je suis content de te voir.", "I'm happy to see you."),
    ("fatigué", "adjective", "tired", "Je suis fatigué.", "I'm tired."),
    ("seul", "adjective", "alone, only", "Je suis seul ici.", "I'm alone here."),
    ("plein", "adjective", "full", "Le verre est plein.", "The glass is full."),
    ("vide", "adjective", "empty", "La salle est vide.", "The room is empty."),
    ("chaud", "adjective", "hot, warm", "Le café est chaud.", "The coffee is hot."),
    ("froid", "adjective", "cold", "Il fait froid dehors.", "It's cold outside."),

    # Adverbs / function words worth flashcarding
    ("oui", "adverb", "yes", "Oui, bien sûr.", "Yes, of course."),
    ("non", "adverb", "no", "Non, merci.", "No, thank you."),
    ("peut-être", "adverb", "maybe", "Peut-être demain.", "Maybe tomorrow."),
    ("bien", "adverb", "well", "Ça va bien.", "I'm doing well."),
    ("mal", "adverb", "badly", "Je dors mal.", "I sleep badly."),
    ("très", "adverb", "very", "Très bien.", "Very good."),
    ("beaucoup", "adverb", "a lot, much", "Merci beaucoup.", "Thank you very much."),
    ("peu", "adverb", "little, few", "Je mange peu.", "I eat little."),
    ("trop", "adverb", "too much", "C'est trop cher.", "It's too expensive."),
    ("encore", "adverb", "still, again", "Encore une fois.", "Once again."),
    ("déjà", "adverb", "already", "C'est déjà fait.", "It's already done."),
    ("toujours", "adverb", "always", "Toujours en retard.", "Always late."),
    ("jamais", "adverb", "never", "Je ne fume jamais.", "I never smoke."),
    ("souvent", "adverb", "often", "Je viens souvent ici.", "I often come here."),
    ("ici", "adverb", "here", "Viens ici.", "Come here."),
    ("là", "adverb", "there", "Il est là.", "He is there."),
    ("maintenant", "adverb", "now", "Pas maintenant.", "Not now."),
    ("aujourd'hui", "adverb", "today", "Aujourd'hui, il pleut.", "Today, it's raining."),
    ("hier", "adverb", "yesterday", "Hier, j'ai travaillé.", "Yesterday, I worked."),
    ("demain", "adverb", "tomorrow", "À demain.", "See you tomorrow."),
    ("vite", "adverb", "quickly", "Marche vite.", "Walk fast."),

    # Question words
    ("où", "adverb", "where", "Où vas-tu ?", "Where are you going?"),
    ("quand", "adverb", "when", "Quand arrives-tu ?", "When do you arrive?"),
    ("comment", "adverb", "how", "Comment ça va ?", "How are you?"),
    ("pourquoi", "adverb", "why", "Pourquoi pas ?", "Why not?"),
    ("combien", "adverb", "how much / many", "Combien ça coûte ?", "How much does it cost?"),
]


TOPIC_DECKS = {
    "travel": {
        "lemmas": ["voyager", "voiture", "ville", "pays", "rue", "partir", "arriver"],
        "new_entries": [
            ("voyage", "noun (masc.)", "trip, journey", "Bon voyage !", "Have a good trip!"),
            ("aéroport", "noun (masc.)", "airport", "L'aéroport est loin.", "The airport is far."),
            ("avion", "noun (masc.)", "airplane", "Je prends l'avion demain.", "I'm taking the plane tomorrow."),
            ("train", "noun (masc.)", "train", "Le train est en retard.", "The train is late."),
            ("gare", "noun (fem.)", "train station", "On se retrouve à la gare.", "Let's meet at the station."),
            ("hôtel", "noun (masc.)", "hotel", "L'hôtel est complet.", "The hotel is full."),
            ("billet", "noun (masc.)", "ticket", "J'achète un billet.", "I'm buying a ticket."),
            ("valise", "noun (fem.)", "suitcase", "Ma valise est lourde.", "My suitcase is heavy."),
            ("passeport", "noun (masc.)", "passport", "Montre ton passeport.", "Show your passport."),
            ("bus", "noun (masc.)", "bus", "Je prends le bus.", "I take the bus."),
            ("métro", "noun (masc.)", "subway", "Le métro est rapide.", "The subway is fast."),
            ("taxi", "noun (masc.)", "taxi", "Appelle un taxi.", "Call a taxi."),
            ("plage", "noun (fem.)", "beach", "La plage est belle.", "The beach is beautiful."),
            ("montagne", "noun (fem.)", "mountain", "Nous allons à la montagne.", "We're going to the mountains."),
            ("vacances", "noun (fem. pl.)", "vacation", "Bonnes vacances !", "Have a good vacation!"),
            ("carte", "noun (fem.)", "map, card", "Regarde la carte.", "Look at the map."),
            ("frontière", "noun (fem.)", "border", "On traverse la frontière.", "We're crossing the border."),
        ],
    },
    "food": {
        "lemmas": ["manger", "boire", "pain", "café", "eau", "cuisiner"],
        "new_entries": [
            ("nourriture", "noun (fem.)", "food", "La nourriture est délicieuse.", "The food is delicious."),
            ("repas", "noun (masc.)", "meal", "Le repas est prêt.", "The meal is ready."),
            ("petit-déjeuner", "noun (masc.)", "breakfast", "Je prends mon petit-déjeuner à sept heures.", "I have breakfast at seven."),
            ("déjeuner", "noun (masc.)", "lunch", "À quelle heure est le déjeuner ?", "What time is lunch?"),
            ("dîner", "noun (masc.)", "dinner", "Le dîner est servi.", "Dinner is served."),
            ("vin", "noun (masc.)", "wine", "Un verre de vin rouge.", "A glass of red wine."),
            ("bière", "noun (fem.)", "beer", "Une bière, s'il vous plaît.", "A beer, please."),
            ("lait", "noun (masc.)", "milk", "Du lait dans le café.", "Milk in the coffee."),
            ("fromage", "noun (masc.)", "cheese", "J'aime le fromage français.", "I like French cheese."),
            ("viande", "noun (fem.)", "meat", "Je ne mange pas de viande.", "I don't eat meat."),
            ("poisson", "noun (masc.)", "fish", "Le poisson est frais.", "The fish is fresh."),
            ("légume", "noun (masc.)", "vegetable", "Mange tes légumes.", "Eat your vegetables."),
            ("fruit", "noun (masc.)", "fruit", "J'adore les fruits.", "I love fruit."),
            ("pomme", "noun (fem.)", "apple", "Une pomme par jour.", "An apple a day."),
            ("œuf", "noun (masc.)", "egg", "Deux œufs au plat.", "Two fried eggs."),
            ("sucre", "noun (masc.)", "sugar", "Du sucre dans mon thé.", "Sugar in my tea."),
            ("sel", "noun (masc.)", "salt", "Passe-moi le sel.", "Pass me the salt."),
            ("restaurant", "noun (masc.)", "restaurant", "Allons au restaurant.", "Let's go to the restaurant."),
            ("menu", "noun (masc.)", "menu", "Le menu, s'il vous plaît.", "The menu, please."),
            ("addition", "noun (fem.)", "bill", "L'addition, s'il vous plaît.", "The bill, please."),
            ("délicieux", "adjective", "delicious", "C'est délicieux !", "It's delicious!"),
        ],
    },
    "work": {
        "lemmas": ["travailler", "travail", "bureau"],
        "new_entries": [
            ("réunion", "noun (fem.)", "meeting", "La réunion commence à dix heures.", "The meeting starts at ten."),
            ("projet", "noun (masc.)", "project", "Mon projet est fini.", "My project is finished."),
            ("collègue", "noun (masc./fem.)", "colleague", "Mes collègues sont sympas.", "My colleagues are nice."),
            ("patron", "noun (masc.)", "boss", "Le patron arrive demain.", "The boss arrives tomorrow."),
            ("entreprise", "noun (fem.)", "company", "J'aime mon entreprise.", "I like my company."),
            ("ordinateur", "noun (masc.)", "computer", "Mon ordinateur ne marche pas.", "My computer isn't working."),
            ("téléphone", "noun (masc.)", "phone", "Mon téléphone sonne.", "My phone is ringing."),
            ("email", "noun (masc.)", "email", "J'ai envoyé un email.", "I sent an email."),
            ("salaire", "noun (masc.)", "salary", "Mon salaire est correct.", "My salary is okay."),
            ("client", "noun (masc.)", "client", "Le client attend.", "The client is waiting."),
            ("emploi", "noun (masc.)", "job, employment", "Je cherche un emploi.", "I'm looking for a job."),
            ("équipe", "noun (fem.)", "team", "Mon équipe est forte.", "My team is strong."),
            ("idée", "noun (fem.)", "idea", "J'ai une bonne idée.", "I have a good idea."),
        ],
    },
    "family": {
        "lemmas": ["famille", "père", "mère", "frère", "sœur", "fils", "fille", "enfant", "ami", "amie", "homme", "femme", "personne", "gens"],
        "new_entries": [
            ("grand-père", "noun (masc.)", "grandfather", "Mon grand-père raconte des histoires.", "My grandfather tells stories."),
            ("grand-mère", "noun (fem.)", "grandmother", "Ma grand-mère fait des gâteaux.", "My grandmother makes cakes."),
            ("oncle", "noun (masc.)", "uncle", "Mon oncle est gentil.", "My uncle is kind."),
            ("tante", "noun (fem.)", "aunt", "Ma tante habite à Marseille.", "My aunt lives in Marseille."),
            ("cousin", "noun (masc.)", "cousin (male)", "Mon cousin a mon âge.", "My cousin is my age."),
            ("cousine", "noun (fem.)", "cousin (female)", "Ma cousine est étudiante.", "My cousin is a student."),
            ("mari", "noun (masc.)", "husband", "Mon mari travaille beaucoup.", "My husband works a lot."),
            ("épouse", "noun (fem.)", "wife", "Mon épouse est médecin.", "My wife is a doctor."),
            ("bébé", "noun (masc.)", "baby", "Le bébé dort.", "The baby is sleeping."),
            ("voisin", "noun (masc.)", "neighbor", "Mon voisin est sympa.", "My neighbor is nice."),
        ],
    },
    "home": {
        "lemmas": ["maison", "rue"],
        "new_entries": [
            ("chambre", "noun (fem.)", "bedroom", "Ma chambre est petite.", "My bedroom is small."),
            ("cuisine", "noun (fem.)", "kitchen", "La cuisine est en bas.", "The kitchen is downstairs."),
            ("salon", "noun (masc.)", "living room", "On regarde la télé au salon.", "We watch TV in the living room."),
            ("salle de bain", "noun (fem.)", "bathroom", "La salle de bain est libre.", "The bathroom is free."),
            ("toilettes", "noun (fem. pl.)", "toilet", "Où sont les toilettes ?", "Where is the toilet?"),
            ("porte", "noun (fem.)", "door", "Ferme la porte.", "Close the door."),
            ("fenêtre", "noun (fem.)", "window", "Ouvre la fenêtre.", "Open the window."),
            ("table", "noun (fem.)", "table", "Mets la table.", "Set the table."),
            ("chaise", "noun (fem.)", "chair", "Assieds-toi sur la chaise.", "Sit on the chair."),
            ("lit", "noun (masc.)", "bed", "Va au lit.", "Go to bed."),
            ("clé", "noun (fem.)", "key", "J'ai perdu mes clés.", "I lost my keys."),
            ("lumière", "noun (fem.)", "light", "Allume la lumière.", "Turn on the light."),
            ("mur", "noun (masc.)", "wall", "Le mur est blanc.", "The wall is white."),
            ("toit", "noun (masc.)", "roof", "Un chat sur le toit.", "A cat on the roof."),
            ("jardin", "noun (masc.)", "garden", "On mange dans le jardin.", "We eat in the garden."),
            ("appartement", "noun (masc.)", "apartment", "Mon appartement est au deuxième étage.", "My apartment is on the second floor."),
        ],
    },
    "body_health": {
        "lemmas": ["main", "œil", "dormir"],
        "new_entries": [
            ("tête", "noun (fem.)", "head", "J'ai mal à la tête.", "I have a headache."),
            ("cheveux", "noun (masc. pl.)", "hair", "Elle a les cheveux longs.", "She has long hair."),
            ("visage", "noun (masc.)", "face", "Lave-toi le visage.", "Wash your face."),
            ("bouche", "noun (fem.)", "mouth", "Ouvre la bouche.", "Open your mouth."),
            ("nez", "noun (masc.)", "nose", "J'ai le nez bouché.", "My nose is blocked."),
            ("oreille", "noun (fem.)", "ear", "J'ai mal à l'oreille.", "My ear hurts."),
            ("dent", "noun (fem.)", "tooth", "Brosse-toi les dents.", "Brush your teeth."),
            ("bras", "noun (masc.)", "arm", "Lève le bras.", "Raise your arm."),
            ("jambe", "noun (fem.)", "leg", "Ma jambe me fait mal.", "My leg hurts."),
            ("pied", "noun (masc.)", "foot", "À pied, c'est plus rapide.", "On foot, it's faster."),
            ("cœur", "noun (masc.)", "heart", "Mon cœur bat vite.", "My heart is beating fast."),
            ("ventre", "noun (masc.)", "stomach", "J'ai mal au ventre.", "I have a stomachache."),
            ("malade", "adjective", "sick", "Je suis malade aujourd'hui.", "I'm sick today."),
            ("santé", "noun (fem.)", "health", "La santé d'abord.", "Health first."),
            ("médecin", "noun (masc.)", "doctor", "Le médecin est arrivé.", "The doctor has arrived."),
            ("hôpital", "noun (masc.)", "hospital", "Il est à l'hôpital.", "He's at the hospital."),
            ("médicament", "noun (masc.)", "medicine", "Prends ce médicament.", "Take this medicine."),
            ("douleur", "noun (fem.)", "pain", "La douleur diminue.", "The pain is going down."),
        ],
    },
    "time_numbers": {
        "lemmas": ["jour", "nuit", "matin", "soir", "semaine", "mois", "année", "an", "heure", "minute", "moment", "temps", "fois", "hier", "aujourd'hui", "demain", "maintenant"],
        "new_entries": [
            ("seconde", "noun (fem.)", "second", "Attends une seconde.", "Wait a second."),
            ("lundi", "noun (masc.)", "Monday", "Lundi, je travaille.", "On Monday, I work."),
            ("mardi", "noun (masc.)", "Tuesday", "Mardi prochain.", "Next Tuesday."),
            ("mercredi", "noun (masc.)", "Wednesday", "On se voit mercredi.", "Let's meet Wednesday."),
            ("jeudi", "noun (masc.)", "Thursday", "Jeudi soir.", "Thursday evening."),
            ("vendredi", "noun (masc.)", "Friday", "Vendredi est mon jour préféré.", "Friday is my favorite day."),
            ("samedi", "noun (masc.)", "Saturday", "Samedi, on sort.", "On Saturday, we go out."),
            ("dimanche", "noun (masc.)", "Sunday", "Dimanche, je me repose.", "On Sunday, I rest."),
            ("un", "number", "one", "Un café.", "One coffee."),
            ("deux", "number", "two", "Deux frères.", "Two brothers."),
            ("trois", "number", "three", "Trois enfants.", "Three children."),
            ("quatre", "number", "four", "Quatre saisons.", "Four seasons."),
            ("cinq", "number", "five", "Cinq euros.", "Five euros."),
            ("dix", "number", "ten", "Dix minutes.", "Ten minutes."),
            ("cent", "number", "hundred", "Cent ans.", "A hundred years."),
            ("mille", "number", "thousand", "Mille mercis.", "A thousand thanks."),
        ],
    },
    "money_shopping": {
        "lemmas": ["payer", "acheter", "vendre"],
        "new_entries": [
            ("argent", "noun (masc.)", "money", "Je n'ai pas d'argent.", "I don't have money."),
            ("euro", "noun (masc.)", "euro", "Dix euros, s'il vous plaît.", "Ten euros, please."),
            ("prix", "noun (masc.)", "price", "Le prix est correct.", "The price is fair."),
            ("magasin", "noun (masc.)", "shop", "Le magasin ferme à huit heures.", "The shop closes at eight."),
            ("marché", "noun (masc.)", "market", "Je vais au marché.", "I'm going to the market."),
            ("carte bancaire", "noun (fem.)", "credit card", "Je paie par carte bancaire.", "I pay by credit card."),
            ("espèces", "noun (fem. pl.)", "cash", "En espèces ou par carte ?", "Cash or card?"),
            ("monnaie", "noun (fem.)", "change, currency", "Tu as de la monnaie ?", "Do you have change?"),
            ("cher", "adjective", "expensive", "C'est trop cher.", "It's too expensive."),
            ("bon marché", "adjective", "cheap", "Ce restaurant est bon marché.", "This restaurant is cheap."),
            ("gratuit", "adjective", "free", "L'entrée est gratuite.", "Entry is free."),
            ("vêtement", "noun (masc.)", "clothing item", "J'achète des vêtements.", "I'm buying clothes."),
            ("chemise", "noun (fem.)", "shirt", "Une chemise blanche.", "A white shirt."),
            ("chaussure", "noun (fem.)", "shoe", "Mes chaussures sont neuves.", "My shoes are new."),
            ("sac", "noun (masc.)", "bag", "Mon sac est lourd.", "My bag is heavy."),
        ],
    },
    "feelings": {
        "lemmas": ["aimer", "heureux", "triste", "content", "fatigué"],
        "new_entries": [
            ("peur", "noun (fem.)", "fear", "J'ai peur du noir.", "I'm afraid of the dark."),
            ("colère", "noun (fem.)", "anger", "Il est en colère.", "He is angry."),
            ("joie", "noun (fem.)", "joy", "Quelle joie de te voir.", "What a joy to see you."),
            ("amour", "noun (masc.)", "love", "L'amour, c'est tout.", "Love is everything."),
            ("inquiet", "adjective", "worried", "Je suis inquiet pour toi.", "I'm worried about you."),
            ("calme", "adjective", "calm", "Reste calme.", "Stay calm."),
            ("nerveux", "adjective", "nervous", "Je suis nerveux avant l'examen.", "I'm nervous before the exam."),
            ("surpris", "adjective", "surprised", "Je suis très surpris.", "I'm very surprised."),
            ("fier", "adjective", "proud", "Je suis fier de toi.", "I'm proud of you."),
            ("amoureux", "adjective", "in love", "Il est amoureux.", "He is in love."),
            ("ennuyé", "adjective", "bored", "Je suis ennuyé.", "I'm bored."),
            ("excité", "adjective", "excited", "Les enfants sont excités.", "The kids are excited."),
            ("rire", "verb", "to laugh", "On a beaucoup ri.", "We laughed a lot."),
            ("pleurer", "verb", "to cry", "Ne pleure pas.", "Don't cry."),
            ("sourire", "verb", "to smile", "Souris pour la photo.", "Smile for the photo."),
        ],
    },
    "nature_weather": {
        "lemmas": [],
        "new_entries": [
            ("soleil", "noun (masc.)", "sun", "Le soleil brille.", "The sun is shining."),
            ("lune", "noun (fem.)", "moon", "La lune est pleine.", "The moon is full."),
            ("étoile", "noun (fem.)", "star", "Les étoiles brillent.", "The stars are shining."),
            ("ciel", "noun (masc.)", "sky", "Le ciel est bleu.", "The sky is blue."),
            ("nuage", "noun (masc.)", "cloud", "Il y a des nuages.", "There are clouds."),
            ("pluie", "noun (fem.)", "rain", "La pluie tombe fort.", "The rain is falling hard."),
            ("neige", "noun (fem.)", "snow", "La neige est blanche.", "The snow is white."),
            ("vent", "noun (masc.)", "wind", "Le vent souffle.", "The wind is blowing."),
            ("arbre", "noun (masc.)", "tree", "Un grand arbre dans le jardin.", "A big tree in the garden."),
            ("fleur", "noun (fem.)", "flower", "Des fleurs sur la table.", "Flowers on the table."),
            ("rivière", "noun (fem.)", "river", "La rivière est froide.", "The river is cold."),
            ("mer", "noun (fem.)", "sea", "On va à la mer.", "We're going to the sea."),
            ("forêt", "noun (fem.)", "forest", "On se promène dans la forêt.", "We walk in the forest."),
            ("animal", "noun (masc.)", "animal", "J'aime les animaux.", "I love animals."),
            ("chien", "noun (masc.)", "dog", "Mon chien est gentil.", "My dog is friendly."),
            ("chat", "noun (masc.)", "cat", "Le chat dort sur le canapé.", "The cat is sleeping on the sofa."),
            ("oiseau", "noun (masc.)", "bird", "L'oiseau chante.", "The bird is singing."),
            ("printemps", "noun (masc.)", "spring", "Au printemps, tout fleurit.", "In spring, everything blooms."),
            ("été", "noun (masc.)", "summer", "L'été est chaud.", "Summer is hot."),
            ("automne", "noun (masc.)", "autumn", "En automne, il pleut.", "In autumn, it rains."),
            ("hiver", "noun (masc.)", "winter", "L'hiver est froid.", "Winter is cold."),
        ],
    },
}


if __name__ == "__main__":
    build_dataset(
        language_code="fr",
        output_filename="french_top1000.json",
        entries=ENTRIES,
        topic_decks=TOPIC_DECKS,
        generated_glob="generated_entries_fr*.json",
    )
