#!/usr/bin/env python3
"""Generate italian_top1000.json — native-frequency-ordered starter set.

Build-time tool. Run:
    python3 tools/build_italian.py

Frequency ordering inspired by hermitdave/FrequencyWords (MIT) and
Lo Cascio "A Frequency Dictionary of Italian". Examples authored from
scratch.
"""

from vocab_pipeline import build_dataset


# (lemma, part_of_speech, english_gloss, italian_example, english_translation)
ENTRIES: list[tuple[str, str, str, str, str]] = [
    # Essential verbs
    ("essere", "verb", "to be", "Sono uno studente.", "I am a student."),
    ("avere", "verb", "to have", "Ho fame.", "I'm hungry."),
    ("fare", "verb", "to do, to make", "Cosa fai?", "What are you doing?"),
    ("dire", "verb", "to say", "Dimmi la verità.", "Tell me the truth."),
    ("andare", "verb", "to go", "Vado al mercato.", "I'm going to the market."),
    ("potere", "verb", "to be able, can", "Non posso venire.", "I can't come."),
    ("volere", "verb", "to want", "Voglio un caffè.", "I want a coffee."),
    ("sapere", "verb", "to know (a fact)", "Non lo so.", "I don't know."),
    ("dovere", "verb", "must, to have to", "Devo lavorare.", "I have to work."),
    ("vedere", "verb", "to see", "Voglio vedere il film.", "I want to see the film."),
    ("dare", "verb", "to give", "Dammi la mano.", "Give me your hand."),
    ("stare", "verb", "to stay, to be (state)", "Sto bene.", "I'm fine."),
    ("venire", "verb", "to come", "Vieni qui.", "Come here."),
    ("parlare", "verb", "to speak", "Parlo due lingue.", "I speak two languages."),
    ("trovare", "verb", "to find", "Non trovo le chiavi.", "I can't find the keys."),
    ("sentire", "verb", "to hear, to feel", "Mi senti?", "Can you hear me?"),
    ("lasciare", "verb", "to leave, to let", "Lasciami in pace.", "Leave me alone."),
    ("prendere", "verb", "to take", "Prendo l'autobus.", "I'm taking the bus."),
    ("guardare", "verb", "to look at, to watch", "Guarda il cielo.", "Look at the sky."),
    ("pensare", "verb", "to think", "Cosa pensi?", "What do you think?"),
    ("passare", "verb", "to pass, to spend (time)", "Passo da te dopo.", "I'll come by your place later."),
    ("credere", "verb", "to believe", "Credo di sì.", "I think so."),
    ("portare", "verb", "to bring, to carry", "Porta il libro.", "Bring the book."),
    ("mettere", "verb", "to put", "Metti il libro sul tavolo.", "Put the book on the table."),
    ("amare", "verb", "to love", "Amo la mia famiglia.", "I love my family."),
    ("piacere", "verb", "to like, to please", "Mi piace il caffè.", "I like coffee."),
    ("aspettare", "verb", "to wait", "Aspettami.", "Wait for me."),
    ("cercare", "verb", "to look for", "Cerco il mio telefono.", "I'm looking for my phone."),
    ("chiamare", "verb", "to call", "Mi chiamo Marco.", "My name is Marco."),
    ("conoscere", "verb", "to know (a person/place)", "Conosco tua sorella.", "I know your sister."),
    ("vivere", "verb", "to live", "Vivo a Roma.", "I live in Rome."),
    ("uscire", "verb", "to go out", "Esco stasera.", "I'm going out tonight."),
    ("entrare", "verb", "to enter", "Entra, per favore.", "Come in, please."),
    ("arrivare", "verb", "to arrive", "Il treno arriva alle otto.", "The train arrives at eight."),
    ("partire", "verb", "to leave, to depart", "Parto domani.", "I leave tomorrow."),
    ("tornare", "verb", "to return", "Torno fra un'ora.", "I'll be back in an hour."),
    ("rimanere", "verb", "to remain, to stay", "Rimango a casa.", "I'm staying home."),
    ("seguire", "verb", "to follow", "Seguimi.", "Follow me."),
    ("scrivere", "verb", "to write", "Scrivo una lettera.", "I'm writing a letter."),
    ("leggere", "verb", "to read", "Leggo ogni sera.", "I read every evening."),
    ("imparare", "verb", "to learn", "Voglio imparare l'italiano.", "I want to learn Italian."),
    ("studiare", "verb", "to study", "Studio per l'esame.", "I'm studying for the exam."),
    ("lavorare", "verb", "to work", "Lavoro in un ufficio.", "I work in an office."),
    ("ascoltare", "verb", "to listen", "Ascolto musica ogni giorno.", "I listen to music every day."),
    ("ricordare", "verb", "to remember", "Ricordo quel giorno.", "I remember that day."),
    ("dimenticare", "verb", "to forget", "Ho dimenticato il suo nome.", "I forgot his name."),
    ("finire", "verb", "to finish", "Finisco il lavoro.", "I'll finish the work."),
    ("cominciare", "verb", "to begin", "La lezione comincia ora.", "The class starts now."),
    ("mangiare", "verb", "to eat", "Andiamo a mangiare.", "Let's go eat."),
    ("bere", "verb", "to drink", "Bevo acqua ogni giorno.", "I drink water every day."),
    ("dormire", "verb", "to sleep", "Dormo otto ore.", "I sleep eight hours."),
    ("giocare", "verb", "to play", "I bambini giocano al parco.", "The children play in the park."),
    ("correre", "verb", "to run", "Corro ogni mattina.", "I run every morning."),
    ("camminare", "verb", "to walk", "Camminiamo sulla spiaggia.", "We walk on the beach."),
    ("viaggiare", "verb", "to travel", "Mi piace viaggiare.", "I like to travel."),
    ("guidare", "verb", "to drive", "Guido al lavoro.", "I drive to work."),
    ("pagare", "verb", "to pay", "Pago con la carta.", "I pay by card."),
    ("comprare", "verb", "to buy", "Compro il pane.", "I'm buying bread."),
    ("vendere", "verb", "to sell", "Vendono frutta al mercato.", "They sell fruit at the market."),
    ("aprire", "verb", "to open", "Apri la finestra.", "Open the window."),
    ("chiudere", "verb", "to close", "Chiudi la porta.", "Close the door."),
    ("cambiare", "verb", "to change", "Voglio cambiare lavoro.", "I want to change jobs."),
    ("aiutare", "verb", "to help", "Mi puoi aiutare?", "Can you help me?"),
    ("usare", "verb", "to use", "Uso il telefono ogni giorno.", "I use the phone every day."),
    ("provare", "verb", "to try", "Prova ancora.", "Try again."),
    ("cantare", "verb", "to sing", "Cantiamo alla festa.", "We sing at the party."),
    ("ballare", "verb", "to dance", "Ballo il sabato.", "I dance on Saturdays."),
    ("cucinare", "verb", "to cook", "Mio padre cucina bene.", "My father cooks well."),
    ("vincere", "verb", "to win", "Abbiamo vinto la partita.", "We won the game."),
    ("perdere", "verb", "to lose", "Ho perso le chiavi.", "I lost my keys."),
    ("spiegare", "verb", "to explain", "Spiegami il problema.", "Explain the problem to me."),
    ("raccontare", "verb", "to tell (a story)", "Raccontami una storia.", "Tell me a story."),
    ("rispondere", "verb", "to answer", "Rispondi alla domanda.", "Answer the question."),
    ("chiedere", "verb", "to ask", "Ti chiedo aiuto.", "I'm asking you for help."),
    ("sognare", "verb", "to dream", "Ho sognato di te.", "I dreamed about you."),
    ("baciare", "verb", "to kiss", "Mi ha baciato.", "He kissed me."),

    # People / family nouns
    ("uomo", "noun (masc.)", "man", "Quell'uomo è alto.", "That man is tall."),
    ("donna", "noun (fem.)", "woman", "Quella donna è mia zia.", "That woman is my aunt."),
    ("bambino", "noun (masc.)", "child, boy", "Il bambino gioca con il cane.", "The child plays with the dog."),
    ("bambina", "noun (fem.)", "girl, female child", "La bambina ha cinque anni.", "The girl is five years old."),
    ("figlio", "noun (masc.)", "son", "Mio figlio studia molto.", "My son studies a lot."),
    ("figlia", "noun (fem.)", "daughter", "Mia figlia suona la chitarra.", "My daughter plays guitar."),
    ("padre", "noun (masc.)", "father", "Mio padre è medico.", "My father is a doctor."),
    ("madre", "noun (fem.)", "mother", "Mia madre cucina bene.", "My mother cooks well."),
    ("fratello", "noun (masc.)", "brother", "Mio fratello vive a Milano.", "My brother lives in Milan."),
    ("sorella", "noun (fem.)", "sister", "Mia sorella è insegnante.", "My sister is a teacher."),
    ("amico", "noun (masc.)", "friend (male)", "Il mio migliore amico si chiama Luca.", "My best friend's name is Luca."),
    ("amica", "noun (fem.)", "friend (female)", "La mia amica arriva stasera.", "My friend arrives tonight."),
    ("famiglia", "noun (fem.)", "family", "La mia famiglia è grande.", "My family is big."),
    ("gente", "noun (fem.)", "people", "C'è molta gente qui.", "There are a lot of people here."),
    ("persona", "noun (fem.)", "person", "È una brava persona.", "He is a good person."),
    ("ragazzo", "noun (masc.)", "boy, young man", "Il ragazzo studia.", "The boy is studying."),
    ("ragazza", "noun (fem.)", "girl, young woman", "La ragazza è simpatica.", "The girl is friendly."),

    # Time nouns
    ("giorno", "noun (masc.)", "day", "Buongiorno.", "Good morning."),
    ("notte", "noun (fem.)", "night", "Buonanotte.", "Good night."),
    ("mattina", "noun (fem.)", "morning", "Domani mattina.", "Tomorrow morning."),
    ("sera", "noun (fem.)", "evening", "Buonasera.", "Good evening."),
    ("settimana", "noun (fem.)", "week", "Ci vediamo la prossima settimana.", "See you next week."),
    ("mese", "noun (masc.)", "month", "Questo mese è maggio.", "This month is May."),
    ("anno", "noun (masc.)", "year", "Ho vent'anni.", "I'm twenty years old."),
    ("ora", "noun (fem.)", "hour, time", "Che ora è?", "What time is it?"),
    ("minuto", "noun (masc.)", "minute", "Aspetta un minuto.", "Wait a minute."),
    ("momento", "noun (masc.)", "moment", "Un momento, per favore.", "One moment, please."),
    ("tempo", "noun (masc.)", "time; weather", "Non ho tempo.", "I don't have time."),
    ("volta", "noun (fem.)", "time, occasion", "Per la prima volta.", "For the first time."),

    # Places
    ("casa", "noun (fem.)", "house, home", "Vado a casa.", "I'm going home."),
    ("strada", "noun (fem.)", "street, road", "Abito in questa strada.", "I live on this street."),
    ("via", "noun (fem.)", "street, way", "In via Roma.", "On Rome Street."),
    ("città", "noun (fem.)", "city", "Roma è una grande città.", "Rome is a big city."),
    ("paese", "noun (masc.)", "country, village", "Visito un altro paese.", "I'm visiting another country."),
    ("mondo", "noun (masc.)", "world", "Il migliore del mondo.", "The best in the world."),
    ("posto", "noun (masc.)", "place, seat", "Questo posto è bello.", "This place is nice."),
    ("scuola", "noun (fem.)", "school", "Vado a scuola.", "I'm going to school."),
    ("lavoro", "noun (masc.)", "work, job", "Il mio lavoro è difficile.", "My job is hard."),
    ("ufficio", "noun (masc.)", "office", "L'ufficio è chiuso.", "The office is closed."),

    # Common nouns
    ("cosa", "noun (fem.)", "thing", "Cosa fai stasera?", "What are you doing tonight?"),
    ("vita", "noun (fem.)", "life", "La vita è bella.", "Life is beautiful."),
    ("mano", "noun (fem.)", "hand", "Dammi la mano.", "Give me your hand."),
    ("occhio", "noun (masc.)", "eye", "Ha gli occhi azzurri.", "He has blue eyes."),
    ("macchina", "noun (fem.)", "car, machine", "La mia macchina è rossa.", "My car is red."),
    ("acqua", "noun (fem.)", "water", "Un bicchiere d'acqua, per favore.", "A glass of water, please."),
    ("pane", "noun (masc.)", "bread", "Compro il pane.", "I'm buying bread."),
    ("caffè", "noun (masc.)", "coffee", "Un caffè, per favore.", "A coffee, please."),
    ("nome", "noun (masc.)", "name", "Qual è il tuo nome?", "What is your name?"),
    ("storia", "noun (fem.)", "story, history", "Una bella storia.", "A nice story."),
    ("parte", "noun (fem.)", "part", "Una parte del libro.", "A part of the book."),

    # Adjectives
    ("buono", "adjective", "good", "Questo cibo è buono.", "This food is good."),
    ("cattivo", "adjective", "bad", "Un cattivo segno.", "A bad sign."),
    ("grande", "adjective", "big", "Una grande casa.", "A big house."),
    ("piccolo", "adjective", "small", "Una piccola stanza.", "A small room."),
    ("bello", "adjective", "beautiful", "Che bella giornata!", "What a beautiful day!"),
    ("brutto", "adjective", "ugly", "Il tempo è brutto oggi.", "The weather is bad today."),
    ("giovane", "adjective", "young", "È molto giovane.", "She is very young."),
    ("vecchio", "adjective", "old", "Un vecchio libro.", "An old book."),
    ("nuovo", "adjective", "new", "Ho un nuovo lavoro.", "I have a new job."),
    ("primo", "adjective", "first", "È la sua prima volta.", "It's his first time."),
    ("ultimo", "adjective", "last", "L'ultima possibilità.", "The last chance."),
    ("altro", "adjective", "other, another", "Un altro giorno.", "Another day."),
    ("stesso", "adjective", "same", "Lo stesso problema.", "The same problem."),
    ("importante", "adjective", "important", "È importante per me.", "It's important to me."),
    ("possibile", "adjective", "possible", "Non è possibile.", "It's not possible."),
    ("facile", "adjective", "easy", "È facile.", "It's easy."),
    ("difficile", "adjective", "difficult", "È difficile da capire.", "It's hard to understand."),
    ("felice", "adjective", "happy", "Sono felice.", "I'm happy."),
    ("triste", "adjective", "sad", "Perché sei triste?", "Why are you sad?"),
    ("contento", "adjective", "pleased", "Sono contento di vederti.", "I'm happy to see you."),
    ("stanco", "adjective", "tired", "Sono stanco.", "I'm tired."),
    ("solo", "adjective", "alone, only", "Sono solo qui.", "I'm alone here."),
    ("pieno", "adjective", "full", "Il bicchiere è pieno.", "The glass is full."),
    ("vuoto", "adjective", "empty", "La stanza è vuota.", "The room is empty."),
    ("caldo", "adjective", "hot", "Il caffè è caldo.", "The coffee is hot."),
    ("freddo", "adjective", "cold", "Fa freddo fuori.", "It's cold outside."),

    # Adverbs / connectors / interjections
    ("sì", "adverb", "yes", "Sì, certo.", "Yes, of course."),
    ("no", "adverb", "no", "No, grazie.", "No, thank you."),
    ("forse", "adverb", "maybe", "Forse domani.", "Maybe tomorrow."),
    ("bene", "adverb", "well", "Sto bene.", "I'm doing well."),
    ("male", "adverb", "badly", "Dormo male.", "I sleep badly."),
    ("molto", "adverb", "very, much", "Molto bene.", "Very good."),
    ("poco", "adverb", "little, few", "Mangio poco.", "I eat little."),
    ("troppo", "adverb", "too much", "È troppo caro.", "It's too expensive."),
    ("ancora", "adverb", "still, yet, again", "Ancora una volta.", "Once again."),
    ("già", "adverb", "already", "È già fatto.", "It's already done."),
    ("sempre", "adverb", "always", "Sempre in ritardo.", "Always late."),
    ("mai", "adverb", "never", "Non fumo mai.", "I never smoke."),
    ("spesso", "adverb", "often", "Vengo spesso qui.", "I often come here."),
    ("qui", "adverb", "here", "Vieni qui.", "Come here."),
    ("là", "adverb", "there", "È là.", "He is there."),
    ("adesso", "adverb", "now", "Non adesso.", "Not now."),
    ("ora", "adverb", "now", "Vieni ora.", "Come now."),
    ("oggi", "adverb", "today", "Oggi piove.", "Today it's raining."),
    ("ieri", "adverb", "yesterday", "Ieri ho lavorato.", "Yesterday I worked."),
    ("domani", "adverb", "tomorrow", "A domani.", "See you tomorrow."),
    ("presto", "adverb", "early, soon", "Mi alzo presto.", "I get up early."),
    ("tardi", "adverb", "late", "Sono in ritardo.", "I'm late."),

    # Question words
    ("dove", "adverb", "where", "Dove vai?", "Where are you going?"),
    ("quando", "adverb", "when", "Quando arrivi?", "When do you arrive?"),
    ("come", "adverb", "how", "Come stai?", "How are you?"),
    ("perché", "adverb", "why; because", "Perché no?", "Why not?"),
    ("quanto", "adverb", "how much", "Quanto costa?", "How much does it cost?"),
]


TOPIC_DECKS = {
    "travel": {
        "lemmas": ["viaggiare", "macchina", "città", "paese", "strada", "partire", "arrivare"],
        "new_entries": [
            ("viaggio", "noun (masc.)", "trip, journey", "Buon viaggio!", "Have a good trip!"),
            ("aeroporto", "noun (masc.)", "airport", "L'aeroporto è lontano.", "The airport is far."),
            ("aereo", "noun (masc.)", "airplane", "Prendo l'aereo domani.", "I'm taking the plane tomorrow."),
            ("treno", "noun (masc.)", "train", "Il treno è in ritardo.", "The train is late."),
            ("stazione", "noun (fem.)", "train station", "Ci vediamo in stazione.", "Let's meet at the station."),
            ("albergo", "noun (masc.)", "hotel", "L'albergo è pieno.", "The hotel is full."),
            ("biglietto", "noun (masc.)", "ticket", "Compro un biglietto.", "I'm buying a ticket."),
            ("valigia", "noun (fem.)", "suitcase", "La mia valigia è pesante.", "My suitcase is heavy."),
            ("passaporto", "noun (masc.)", "passport", "Mostra il passaporto.", "Show your passport."),
            ("autobus", "noun (masc.)", "bus", "Prendo l'autobus.", "I take the bus."),
            ("metropolitana", "noun (fem.)", "subway", "La metropolitana è veloce.", "The subway is fast."),
            ("taxi", "noun (masc.)", "taxi", "Chiama un taxi.", "Call a taxi."),
            ("spiaggia", "noun (fem.)", "beach", "La spiaggia è bella.", "The beach is beautiful."),
            ("montagna", "noun (fem.)", "mountain", "Andiamo in montagna.", "We're going to the mountains."),
            ("vacanza", "noun (fem.)", "vacation", "Buone vacanze!", "Have a good vacation!"),
            ("mappa", "noun (fem.)", "map", "Guarda la mappa.", "Look at the map."),
            ("estero", "noun (masc.)", "abroad", "Vivo all'estero.", "I live abroad."),
        ],
    },
    "food": {
        "lemmas": ["mangiare", "bere", "pane", "caffè", "acqua", "cucinare"],
        "new_entries": [
            ("cibo", "noun (masc.)", "food", "Il cibo è delizioso.", "The food is delicious."),
            ("pasto", "noun (masc.)", "meal", "Il pasto è pronto.", "The meal is ready."),
            ("colazione", "noun (fem.)", "breakfast", "Faccio colazione alle sette.", "I have breakfast at seven."),
            ("pranzo", "noun (masc.)", "lunch", "A che ora è il pranzo?", "What time is lunch?"),
            ("cena", "noun (fem.)", "dinner", "La cena è servita.", "Dinner is served."),
            ("vino", "noun (masc.)", "wine", "Un bicchiere di vino rosso.", "A glass of red wine."),
            ("birra", "noun (fem.)", "beer", "Una birra, per favore.", "A beer, please."),
            ("latte", "noun (masc.)", "milk", "Latte nel caffè.", "Milk in the coffee."),
            ("formaggio", "noun (masc.)", "cheese", "Amo il formaggio italiano.", "I love Italian cheese."),
            ("carne", "noun (fem.)", "meat", "Non mangio carne.", "I don't eat meat."),
            ("pesce", "noun (masc.)", "fish", "Il pesce è fresco.", "The fish is fresh."),
            ("verdura", "noun (fem.)", "vegetable", "Mangia le verdure.", "Eat your vegetables."),
            ("frutta", "noun (fem.)", "fruit", "Adoro la frutta.", "I love fruit."),
            ("mela", "noun (fem.)", "apple", "Una mela al giorno.", "An apple a day."),
            ("pasta", "noun (fem.)", "pasta", "Stasera mangiamo pasta.", "Tonight we eat pasta."),
            ("pizza", "noun (fem.)", "pizza", "Andiamo a mangiare la pizza.", "Let's go eat pizza."),
            ("uovo", "noun (masc.)", "egg", "Due uova al tegamino.", "Two fried eggs."),
            ("zucchero", "noun (masc.)", "sugar", "Zucchero nel tè.", "Sugar in the tea."),
            ("sale", "noun (masc.)", "salt", "Passami il sale.", "Pass me the salt."),
            ("ristorante", "noun (masc.)", "restaurant", "Andiamo al ristorante.", "Let's go to the restaurant."),
            ("menù", "noun (masc.)", "menu", "Il menù, per favore.", "The menu, please."),
            ("conto", "noun (masc.)", "bill", "Il conto, per favore.", "The bill, please."),
            ("delizioso", "adjective", "delicious", "È delizioso!", "It's delicious!"),
        ],
    },
    "work": {
        "lemmas": ["lavorare", "lavoro", "ufficio"],
        "new_entries": [
            ("riunione", "noun (fem.)", "meeting", "La riunione comincia alle dieci.", "The meeting starts at ten."),
            ("progetto", "noun (masc.)", "project", "Il mio progetto è finito.", "My project is finished."),
            ("collega", "noun (masc./fem.)", "colleague", "I miei colleghi sono simpatici.", "My colleagues are nice."),
            ("capo", "noun (masc.)", "boss", "Il capo arriva domani.", "The boss arrives tomorrow."),
            ("azienda", "noun (fem.)", "company", "Amo la mia azienda.", "I love my company."),
            ("computer", "noun (masc.)", "computer", "Il mio computer non funziona.", "My computer isn't working."),
            ("telefono", "noun (masc.)", "phone", "Il mio telefono suona.", "My phone is ringing."),
            ("email", "noun (fem.)", "email", "Ho mandato un'email.", "I sent an email."),
            ("stipendio", "noun (masc.)", "salary", "Il mio stipendio è buono.", "My salary is good."),
            ("cliente", "noun (masc.)", "client", "Il cliente aspetta.", "The client is waiting."),
            ("squadra", "noun (fem.)", "team", "La mia squadra è forte.", "My team is strong."),
            ("idea", "noun (fem.)", "idea", "Ho una buona idea.", "I have a good idea."),
            ("impiego", "noun (masc.)", "job, employment", "Cerco un impiego.", "I'm looking for a job."),
        ],
    },
    "family": {
        "lemmas": ["famiglia", "padre", "madre", "fratello", "sorella", "figlio", "figlia", "bambino", "amico", "amica", "uomo", "donna", "persona", "gente", "ragazzo", "ragazza"],
        "new_entries": [
            ("nonno", "noun (masc.)", "grandfather", "Mio nonno racconta storie.", "My grandfather tells stories."),
            ("nonna", "noun (fem.)", "grandmother", "Mia nonna fa i dolci.", "My grandmother makes sweets."),
            ("zio", "noun (masc.)", "uncle", "Mio zio è gentile.", "My uncle is kind."),
            ("zia", "noun (fem.)", "aunt", "Mia zia vive a Napoli.", "My aunt lives in Naples."),
            ("cugino", "noun (masc.)", "cousin (male)", "Mio cugino ha la mia età.", "My cousin is my age."),
            ("cugina", "noun (fem.)", "cousin (female)", "Mia cugina è studentessa.", "My cousin is a student."),
            ("marito", "noun (masc.)", "husband", "Mio marito lavora molto.", "My husband works a lot."),
            ("moglie", "noun (fem.)", "wife", "Mia moglie è dottoressa.", "My wife is a doctor."),
            ("vicino", "noun (masc.)", "neighbor", "Il mio vicino è simpatico.", "My neighbor is nice."),
            ("genitore", "noun (masc.)", "parent", "I miei genitori vivono qui.", "My parents live here."),
        ],
    },
    "home": {
        "lemmas": ["casa", "strada"],
        "new_entries": [
            ("camera", "noun (fem.)", "room, bedroom", "La mia camera è piccola.", "My room is small."),
            ("cucina", "noun (fem.)", "kitchen", "La cucina è in fondo.", "The kitchen is at the back."),
            ("soggiorno", "noun (masc.)", "living room", "Guardiamo la TV in soggiorno.", "We watch TV in the living room."),
            ("bagno", "noun (masc.)", "bathroom", "Il bagno è libero.", "The bathroom is free."),
            ("porta", "noun (fem.)", "door", "Chiudi la porta.", "Close the door."),
            ("finestra", "noun (fem.)", "window", "Apri la finestra.", "Open the window."),
            ("tavolo", "noun (masc.)", "table", "Apparecchia il tavolo.", "Set the table."),
            ("sedia", "noun (fem.)", "chair", "Siediti sulla sedia.", "Sit on the chair."),
            ("letto", "noun (masc.)", "bed", "Vai a letto.", "Go to bed."),
            ("chiave", "noun (fem.)", "key", "Ho perso le chiavi.", "I lost my keys."),
            ("luce", "noun (fem.)", "light", "Accendi la luce.", "Turn on the light."),
            ("muro", "noun (masc.)", "wall", "Il muro è bianco.", "The wall is white."),
            ("tetto", "noun (masc.)", "roof", "Un gatto sul tetto.", "A cat on the roof."),
            ("giardino", "noun (masc.)", "garden", "Mangiamo in giardino.", "We eat in the garden."),
            ("appartamento", "noun (masc.)", "apartment", "Il mio appartamento è al secondo piano.", "My apartment is on the second floor."),
            ("scala", "noun (fem.)", "stairs, ladder", "Sali le scale.", "Go up the stairs."),
        ],
    },
    "body_health": {
        "lemmas": ["mano", "occhio", "dormire"],
        "new_entries": [
            ("testa", "noun (fem.)", "head", "Ho mal di testa.", "I have a headache."),
            ("capelli", "noun (masc. pl.)", "hair", "Ha i capelli lunghi.", "She has long hair."),
            ("viso", "noun (masc.)", "face", "Lava il viso.", "Wash your face."),
            ("bocca", "noun (fem.)", "mouth", "Apri la bocca.", "Open your mouth."),
            ("naso", "noun (masc.)", "nose", "Ho il naso chiuso.", "My nose is blocked."),
            ("orecchio", "noun (masc.)", "ear", "Mi fa male l'orecchio.", "My ear hurts."),
            ("dente", "noun (masc.)", "tooth", "Lavati i denti.", "Brush your teeth."),
            ("braccio", "noun (masc.)", "arm", "Alza il braccio.", "Raise your arm."),
            ("gamba", "noun (fem.)", "leg", "Mi fa male la gamba.", "My leg hurts."),
            ("piede", "noun (masc.)", "foot", "A piedi è più veloce.", "On foot is faster."),
            ("cuore", "noun (masc.)", "heart", "Il mio cuore batte forte.", "My heart is beating hard."),
            ("pancia", "noun (fem.)", "stomach", "Mi fa male la pancia.", "I have a stomachache."),
            ("malato", "adjective", "sick", "Oggi sono malato.", "I'm sick today."),
            ("salute", "noun (fem.)", "health", "La salute prima di tutto.", "Health first."),
            ("medico", "noun (masc.)", "doctor", "Il medico è arrivato.", "The doctor has arrived."),
            ("ospedale", "noun (masc.)", "hospital", "È in ospedale.", "He's in the hospital."),
            ("medicina", "noun (fem.)", "medicine", "Prendi questa medicina.", "Take this medicine."),
            ("dolore", "noun (masc.)", "pain", "Il dolore diminuisce.", "The pain is going down."),
        ],
    },
    "time_numbers": {
        "lemmas": ["giorno", "notte", "mattina", "sera", "settimana", "mese", "anno", "ora", "minuto", "momento", "tempo", "volta", "oggi", "ieri", "domani", "adesso"],
        "new_entries": [
            ("secondo", "noun (masc.)", "second", "Aspetta un secondo.", "Wait a second."),
            ("lunedì", "noun (masc.)", "Monday", "Lunedì lavoro.", "On Monday I work."),
            ("martedì", "noun (masc.)", "Tuesday", "Martedì prossimo.", "Next Tuesday."),
            ("mercoledì", "noun (masc.)", "Wednesday", "Ci vediamo mercoledì.", "Let's meet Wednesday."),
            ("giovedì", "noun (masc.)", "Thursday", "Giovedì sera.", "Thursday evening."),
            ("venerdì", "noun (masc.)", "Friday", "Venerdì è il mio giorno preferito.", "Friday is my favorite day."),
            ("sabato", "noun (masc.)", "Saturday", "Sabato usciamo.", "On Saturday we go out."),
            ("domenica", "noun (fem.)", "Sunday", "Domenica riposo.", "On Sunday I rest."),
            ("uno", "number", "one", "Un caffè.", "One coffee."),
            ("due", "number", "two", "Due fratelli.", "Two brothers."),
            ("tre", "number", "three", "Tre figli.", "Three children."),
            ("quattro", "number", "four", "Quattro stagioni.", "Four seasons."),
            ("cinque", "number", "five", "Cinque euro.", "Five euros."),
            ("dieci", "number", "ten", "Dieci minuti.", "Ten minutes."),
            ("cento", "number", "hundred", "Cento anni.", "A hundred years."),
            ("mille", "number", "thousand", "Mille grazie.", "A thousand thanks."),
        ],
    },
    "money_shopping": {
        "lemmas": ["pagare", "comprare", "vendere"],
        "new_entries": [
            ("soldi", "noun (masc. pl.)", "money", "Non ho soldi.", "I don't have money."),
            ("euro", "noun (masc.)", "euro", "Dieci euro, per favore.", "Ten euros, please."),
            ("prezzo", "noun (masc.)", "price", "Il prezzo è giusto.", "The price is fair."),
            ("negozio", "noun (masc.)", "shop", "Il negozio chiude alle otto.", "The shop closes at eight."),
            ("mercato", "noun (masc.)", "market", "Vado al mercato.", "I'm going to the market."),
            ("carta di credito", "noun (fem.)", "credit card", "Pago con la carta di credito.", "I pay by credit card."),
            ("contanti", "noun (masc. pl.)", "cash", "In contanti o con carta?", "Cash or card?"),
            ("resto", "noun (masc.)", "change (money), rest", "Tieni il resto.", "Keep the change."),
            ("caro", "adjective", "expensive", "È troppo caro.", "It's too expensive."),
            ("economico", "adjective", "cheap", "Questo ristorante è economico.", "This restaurant is cheap."),
            ("gratis", "adjective", "free", "L'ingresso è gratis.", "Entry is free."),
            ("vestito", "noun (masc.)", "dress, clothes", "Un bel vestito.", "A nice dress."),
            ("camicia", "noun (fem.)", "shirt", "Una camicia bianca.", "A white shirt."),
            ("scarpa", "noun (fem.)", "shoe", "Le mie scarpe sono nuove.", "My shoes are new."),
            ("borsa", "noun (fem.)", "bag", "La mia borsa è pesante.", "My bag is heavy."),
            ("regalo", "noun (masc.)", "gift", "Un regalo per te.", "A gift for you."),
        ],
    },
    "feelings": {
        "lemmas": ["amare", "felice", "triste", "contento", "stanco"],
        "new_entries": [
            ("paura", "noun (fem.)", "fear", "Ho paura del buio.", "I'm afraid of the dark."),
            ("rabbia", "noun (fem.)", "anger", "Sento rabbia.", "I feel angry."),
            ("gioia", "noun (fem.)", "joy", "Che gioia vederti.", "What a joy to see you."),
            ("amore", "noun (masc.)", "love", "L'amore è tutto.", "Love is everything."),
            ("preoccupato", "adjective", "worried", "Sono preoccupato per te.", "I'm worried about you."),
            ("calmo", "adjective", "calm", "Stai calmo.", "Stay calm."),
            ("nervoso", "adjective", "nervous", "Sono nervoso per l'esame.", "I'm nervous about the exam."),
            ("sorpreso", "adjective", "surprised", "Sono molto sorpreso.", "I'm very surprised."),
            ("orgoglioso", "adjective", "proud", "Sono orgoglioso di te.", "I'm proud of you."),
            ("innamorato", "adjective", "in love", "È innamorato.", "He is in love."),
            ("annoiato", "adjective", "bored", "Sono annoiato.", "I'm bored."),
            ("eccitato", "adjective", "excited", "I bambini sono eccitati.", "The children are excited."),
            ("ridere", "verb", "to laugh", "Abbiamo riso molto.", "We laughed a lot."),
            ("piangere", "verb", "to cry", "Non piangere.", "Don't cry."),
            ("sorridere", "verb", "to smile", "Sorridi per la foto.", "Smile for the photo."),
            ("arrabbiato", "adjective", "angry", "È arrabbiato con me.", "He's angry with me."),
        ],
    },
    "nature_weather": {
        "lemmas": [],
        "new_entries": [
            ("sole", "noun (masc.)", "sun", "Il sole splende.", "The sun is shining."),
            ("luna", "noun (fem.)", "moon", "La luna è piena.", "The moon is full."),
            ("stella", "noun (fem.)", "star", "Le stelle brillano.", "The stars are shining."),
            ("cielo", "noun (masc.)", "sky", "Il cielo è azzurro.", "The sky is blue."),
            ("nuvola", "noun (fem.)", "cloud", "Ci sono nuvole.", "There are clouds."),
            ("pioggia", "noun (fem.)", "rain", "La pioggia cade forte.", "The rain is falling hard."),
            ("neve", "noun (fem.)", "snow", "La neve è bianca.", "The snow is white."),
            ("vento", "noun (masc.)", "wind", "Il vento soffia.", "The wind is blowing."),
            ("albero", "noun (masc.)", "tree", "Un grande albero in giardino.", "A big tree in the garden."),
            ("fiore", "noun (masc.)", "flower", "Fiori sul tavolo.", "Flowers on the table."),
            ("fiume", "noun (masc.)", "river", "Il fiume è freddo.", "The river is cold."),
            ("mare", "noun (masc.)", "sea", "Andiamo al mare.", "We're going to the sea."),
            ("bosco", "noun (masc.)", "forest, woods", "Camminiamo nel bosco.", "We walk in the woods."),
            ("animale", "noun (masc.)", "animal", "Amo gli animali.", "I love animals."),
            ("cane", "noun (masc.)", "dog", "Il mio cane è simpatico.", "My dog is friendly."),
            ("gatto", "noun (masc.)", "cat", "Il gatto dorme sul divano.", "The cat is sleeping on the sofa."),
            ("uccello", "noun (masc.)", "bird", "L'uccello canta.", "The bird is singing."),
            ("primavera", "noun (fem.)", "spring", "In primavera tutto fiorisce.", "In spring everything blooms."),
            ("estate", "noun (fem.)", "summer", "L'estate è calda.", "Summer is hot."),
            ("autunno", "noun (masc.)", "autumn", "In autunno piove.", "In autumn it rains."),
            ("inverno", "noun (masc.)", "winter", "L'inverno è freddo.", "Winter is cold."),
        ],
    },
}


if __name__ == "__main__":
    build_dataset(
        language_code="it",
        output_filename="italian_top1000.json",
        entries=ENTRIES,
        topic_decks=TOPIC_DECKS,
        generated_glob="generated_entries_it*.json",
    )
