#!/usr/bin/env python3
"""Generate german_top1000.json — native-frequency-ordered starter set.

Build-time tool. Run:
    python3 tools/build_german.py

Frequency ordering inspired by hermitdave/FrequencyWords (MIT) and
"A Frequency Dictionary of German" (Routledge). Examples authored from
scratch.

Notes on convention:
  - Nouns are written capitalised (German orthography) with "noun (der|die|das)"
    so the gloss carries the gender. The lemma matcher normalises to lowercase
    for matching.
  - Separable verbs are listed in their infinitive prefix-attached form (e.g.
    "ankommen"). The matcher checks lemma stems so basic inflections are
    detected.
"""

from vocab_pipeline import build_dataset


# (lemma, part_of_speech, english_gloss, german_example, english_translation)
ENTRIES: list[tuple[str, str, str, str, str]] = [
    # Essential verbs
    ("sein", "verb", "to be", "Ich bin Student.", "I am a student."),
    ("haben", "verb", "to have", "Ich habe Hunger.", "I'm hungry."),
    ("werden", "verb", "to become; will (aux.)", "Es wird kalt.", "It's getting cold."),
    ("können", "verb", "to be able, can", "Ich kann nicht kommen.", "I can't come."),
    ("müssen", "verb", "must, to have to", "Ich muss arbeiten.", "I have to work."),
    ("sagen", "verb", "to say", "Sag mir die Wahrheit.", "Tell me the truth."),
    ("machen", "verb", "to do, to make", "Was machst du?", "What are you doing?"),
    ("geben", "verb", "to give", "Gib mir die Hand.", "Give me your hand."),
    ("kommen", "verb", "to come", "Komm her.", "Come here."),
    ("sollen", "verb", "should", "Du sollst nicht lügen.", "You shouldn't lie."),
    ("wollen", "verb", "to want", "Ich will einen Kaffee.", "I want a coffee."),
    ("gehen", "verb", "to go", "Ich gehe zum Markt.", "I'm going to the market."),
    ("wissen", "verb", "to know (a fact)", "Ich weiß es nicht.", "I don't know."),
    ("sehen", "verb", "to see", "Ich will den Film sehen.", "I want to see the film."),
    ("lassen", "verb", "to let, to leave", "Lass mich in Ruhe.", "Leave me alone."),
    ("stehen", "verb", "to stand", "Ich stehe vor dem Haus.", "I'm standing in front of the house."),
    ("finden", "verb", "to find", "Ich finde meine Schlüssel nicht.", "I can't find my keys."),
    ("bleiben", "verb", "to stay", "Ich bleibe zu Hause.", "I'm staying home."),
    ("liegen", "verb", "to lie, to be located", "Das Buch liegt auf dem Tisch.", "The book is on the table."),
    ("heißen", "verb", "to be called", "Ich heiße Maria.", "My name is Maria."),
    ("denken", "verb", "to think", "Woran denkst du?", "What are you thinking about?"),
    ("nehmen", "verb", "to take", "Ich nehme den Bus.", "I take the bus."),
    ("tun", "verb", "to do", "Was tust du?", "What are you doing?"),
    ("dürfen", "verb", "may, to be allowed", "Darf ich rein?", "May I come in?"),
    ("glauben", "verb", "to believe", "Ich glaube ja.", "I think so."),
    ("halten", "verb", "to hold", "Halt das bitte.", "Hold this, please."),
    ("nennen", "verb", "to call, to name", "Sie nennen ihn Max.", "They call him Max."),
    ("mögen", "verb", "to like", "Ich mag Kaffee.", "I like coffee."),
    ("zeigen", "verb", "to show", "Zeig mir das Foto.", "Show me the photo."),
    ("führen", "verb", "to lead", "Er führt die Gruppe.", "He leads the group."),
    ("sprechen", "verb", "to speak", "Ich spreche zwei Sprachen.", "I speak two languages."),
    ("bringen", "verb", "to bring", "Bring das Buch mit.", "Bring the book along."),
    ("leben", "verb", "to live", "Ich lebe in Berlin.", "I live in Berlin."),
    ("fahren", "verb", "to drive, to ride", "Ich fahre zur Arbeit.", "I drive to work."),
    ("meinen", "verb", "to mean, to think", "Was meinst du damit?", "What do you mean?"),
    ("fragen", "verb", "to ask", "Frag mich nicht.", "Don't ask me."),
    ("kennen", "verb", "to know (a person/thing)", "Ich kenne deine Schwester.", "I know your sister."),
    ("gelten", "verb", "to be valid", "Das gilt für alle.", "That applies to everyone."),
    ("stellen", "verb", "to put (upright)", "Stell die Vase auf den Tisch.", "Put the vase on the table."),
    ("spielen", "verb", "to play", "Die Kinder spielen im Park.", "The children play in the park."),
    ("arbeiten", "verb", "to work", "Ich arbeite im Büro.", "I work in the office."),
    ("brauchen", "verb", "to need", "Ich brauche Hilfe.", "I need help."),
    ("folgen", "verb", "to follow", "Folge mir.", "Follow me."),
    ("lernen", "verb", "to learn", "Ich will Deutsch lernen.", "I want to learn German."),
    ("verstehen", "verb", "to understand", "Ich verstehe nicht.", "I don't understand."),
    ("setzen", "verb", "to set, to put", "Setz dich.", "Sit down."),
    ("bekommen", "verb", "to get, to receive", "Ich bekomme einen Brief.", "I'm getting a letter."),
    ("beginnen", "verb", "to begin", "Der Kurs beginnt jetzt.", "The class starts now."),
    ("erzählen", "verb", "to tell (a story)", "Erzähl mir eine Geschichte.", "Tell me a story."),
    ("versuchen", "verb", "to try", "Versuch es nochmal.", "Try again."),
    ("schreiben", "verb", "to write", "Ich schreibe einen Brief.", "I'm writing a letter."),
    ("erklären", "verb", "to explain", "Erklär mir das Problem.", "Explain the problem to me."),
    ("entstehen", "verb", "to arise, to come into being", "Eine Idee entsteht.", "An idea is forming."),
    ("erkennen", "verb", "to recognize", "Ich erkenne dich nicht.", "I don't recognize you."),
    ("entwickeln", "verb", "to develop", "Wir entwickeln eine App.", "We're developing an app."),
    ("erhalten", "verb", "to receive", "Ich habe ein Geschenk erhalten.", "I received a gift."),
    ("anfangen", "verb", "to start", "Wir fangen jetzt an.", "We're starting now."),
    ("aufhören", "verb", "to stop", "Hör auf zu reden.", "Stop talking."),
    ("ankommen", "verb", "to arrive", "Der Zug kommt um acht an.", "The train arrives at eight."),
    ("aussehen", "verb", "to look (appearance)", "Du siehst müde aus.", "You look tired."),
    ("hören", "verb", "to hear, to listen", "Hörst du mich?", "Can you hear me?"),
    ("essen", "verb", "to eat", "Wir essen jetzt.", "We're eating now."),
    ("trinken", "verb", "to drink", "Ich trinke Wasser.", "I drink water."),
    ("schlafen", "verb", "to sleep", "Ich schlafe acht Stunden.", "I sleep eight hours."),
    ("lesen", "verb", "to read", "Ich lese jeden Abend.", "I read every evening."),
    ("kaufen", "verb", "to buy", "Ich kaufe Brot.", "I'm buying bread."),
    ("verkaufen", "verb", "to sell", "Sie verkaufen Obst.", "They sell fruit."),
    ("öffnen", "verb", "to open", "Öffne das Fenster.", "Open the window."),
    ("schließen", "verb", "to close", "Schließ die Tür.", "Close the door."),
    ("warten", "verb", "to wait", "Warte auf mich.", "Wait for me."),
    ("suchen", "verb", "to search", "Ich suche mein Telefon.", "I'm looking for my phone."),
    ("zahlen", "verb", "to pay", "Ich zahle mit Karte.", "I'm paying by card."),
    ("ändern", "verb", "to change", "Ich will den Job ändern.", "I want to change jobs."),
    ("helfen", "verb", "to help", "Kannst du mir helfen?", "Can you help me?"),
    ("benutzen", "verb", "to use", "Ich benutze das Telefon jeden Tag.", "I use the phone every day."),
    ("singen", "verb", "to sing", "Wir singen auf der Party.", "We sing at the party."),
    ("tanzen", "verb", "to dance", "Ich tanze samstags.", "I dance on Saturdays."),
    ("kochen", "verb", "to cook", "Mein Vater kocht gut.", "My father cooks well."),
    ("laufen", "verb", "to run, to walk", "Ich laufe jeden Morgen.", "I run every morning."),
    ("reisen", "verb", "to travel", "Ich reise gerne.", "I like to travel."),
    ("gewinnen", "verb", "to win", "Wir haben das Spiel gewonnen.", "We won the game."),
    ("verlieren", "verb", "to lose", "Ich habe meine Schlüssel verloren.", "I lost my keys."),
    ("vergessen", "verb", "to forget", "Ich habe seinen Namen vergessen.", "I forgot his name."),
    ("erinnern", "verb", "to remember", "Ich erinnere mich an diesen Tag.", "I remember that day."),
    ("wählen", "verb", "to choose, to elect", "Wähl eine Farbe.", "Choose a colour."),
    ("treffen", "verb", "to meet", "Wir treffen uns morgen.", "We're meeting tomorrow."),
    ("lieben", "verb", "to love", "Ich liebe meine Familie.", "I love my family."),
    ("lachen", "verb", "to laugh", "Wir haben viel gelacht.", "We laughed a lot."),
    ("weinen", "verb", "to cry", "Wein nicht.", "Don't cry."),

    # People / family nouns
    ("Mann", "noun (der)", "man, husband", "Dieser Mann ist groß.", "This man is tall."),
    ("Frau", "noun (die)", "woman, wife", "Diese Frau ist meine Tante.", "This woman is my aunt."),
    ("Kind", "noun (das)", "child", "Das Kind spielt mit dem Hund.", "The child plays with the dog."),
    ("Sohn", "noun (der)", "son", "Mein Sohn ist fünf Jahre alt.", "My son is five years old."),
    ("Tochter", "noun (die)", "daughter", "Meine Tochter spielt Gitarre.", "My daughter plays guitar."),
    ("Vater", "noun (der)", "father", "Mein Vater ist Arzt.", "My father is a doctor."),
    ("Mutter", "noun (die)", "mother", "Meine Mutter kocht gut.", "My mother cooks well."),
    ("Bruder", "noun (der)", "brother", "Mein Bruder lebt in München.", "My brother lives in Munich."),
    ("Schwester", "noun (die)", "sister", "Meine Schwester ist Lehrerin.", "My sister is a teacher."),
    ("Freund", "noun (der)", "friend (male), boyfriend", "Mein bester Freund heißt Tom.", "My best friend's name is Tom."),
    ("Freundin", "noun (die)", "friend (female), girlfriend", "Meine Freundin kommt heute Abend.", "My girlfriend is coming tonight."),
    ("Familie", "noun (die)", "family", "Meine Familie ist groß.", "My family is big."),
    ("Leute", "noun (pl.)", "people", "Hier sind viele Leute.", "There are a lot of people here."),
    ("Person", "noun (die)", "person", "Sie ist eine nette Person.", "She is a nice person."),
    ("Junge", "noun (der)", "boy", "Der Junge lernt fleißig.", "The boy studies diligently."),
    ("Mädchen", "noun (das)", "girl", "Das Mädchen ist sympathisch.", "The girl is friendly."),

    # Time nouns
    ("Tag", "noun (der)", "day", "Guten Tag.", "Good day."),
    ("Nacht", "noun (die)", "night", "Gute Nacht.", "Good night."),
    ("Morgen", "noun (der)", "morning", "Guten Morgen.", "Good morning."),
    ("Abend", "noun (der)", "evening", "Guten Abend.", "Good evening."),
    ("Woche", "noun (die)", "week", "Bis nächste Woche.", "See you next week."),
    ("Monat", "noun (der)", "month", "Dieser Monat ist Mai.", "This month is May."),
    ("Jahr", "noun (das)", "year", "Ich bin zwanzig Jahre alt.", "I'm twenty years old."),
    ("Stunde", "noun (die)", "hour", "Eine Stunde später.", "An hour later."),
    ("Minute", "noun (die)", "minute", "Warte eine Minute.", "Wait a minute."),
    ("Moment", "noun (der)", "moment", "Einen Moment, bitte.", "One moment, please."),
    ("Zeit", "noun (die)", "time", "Ich habe keine Zeit.", "I don't have time."),
    ("Mal", "noun (das)", "time, occasion", "Zum ersten Mal.", "For the first time."),

    # Places
    ("Haus", "noun (das)", "house", "Ich gehe nach Hause.", "I'm going home."),
    ("Straße", "noun (die)", "street", "Ich wohne in dieser Straße.", "I live on this street."),
    ("Stadt", "noun (die)", "city", "Berlin ist eine große Stadt.", "Berlin is a big city."),
    ("Land", "noun (das)", "country, land", "Ich besuche ein anderes Land.", "I'm visiting another country."),
    ("Welt", "noun (die)", "world", "Er ist der Beste der Welt.", "He's the best in the world."),
    ("Ort", "noun (der)", "place", "Dieser Ort ist schön.", "This place is nice."),
    ("Platz", "noun (der)", "square, seat, space", "Auf dem Marktplatz.", "On the market square."),
    ("Schule", "noun (die)", "school", "Ich gehe zur Schule.", "I'm going to school."),
    ("Arbeit", "noun (die)", "work, job", "Meine Arbeit ist schwer.", "My job is hard."),
    ("Büro", "noun (das)", "office", "Das Büro ist geschlossen.", "The office is closed."),

    # Common nouns
    ("Sache", "noun (die)", "thing, matter", "Das ist eine andere Sache.", "That's a different matter."),
    ("Leben", "noun (das)", "life", "Das Leben ist schön.", "Life is beautiful."),
    ("Hand", "noun (die)", "hand", "Gib mir die Hand.", "Give me your hand."),
    ("Auge", "noun (das)", "eye", "Er hat blaue Augen.", "He has blue eyes."),
    ("Auto", "noun (das)", "car", "Mein Auto ist rot.", "My car is red."),
    ("Wasser", "noun (das)", "water", "Ein Glas Wasser, bitte.", "A glass of water, please."),
    ("Brot", "noun (das)", "bread", "Ich kaufe Brot.", "I'm buying bread."),
    ("Kaffee", "noun (der)", "coffee", "Einen Kaffee, bitte.", "A coffee, please."),
    ("Name", "noun (der)", "name", "Wie ist dein Name?", "What is your name?"),
    ("Buch", "noun (das)", "book", "Ich lese ein gutes Buch.", "I'm reading a good book."),
    ("Frage", "noun (die)", "question", "Ich habe eine Frage.", "I have a question."),
    ("Antwort", "noun (die)", "answer", "Eine gute Antwort.", "A good answer."),

    # Adjectives
    ("gut", "adjective", "good", "Es ist sehr gut.", "It's very good."),
    ("schlecht", "adjective", "bad", "Ein schlechtes Zeichen.", "A bad sign."),
    ("groß", "adjective", "big, tall", "Ein großes Haus.", "A big house."),
    ("klein", "adjective", "small", "Ein kleines Zimmer.", "A small room."),
    ("schön", "adjective", "beautiful", "Was für ein schöner Tag.", "What a beautiful day."),
    ("hässlich", "adjective", "ugly", "Das Wetter ist hässlich heute.", "The weather is ugly today."),
    ("jung", "adjective", "young", "Sie ist sehr jung.", "She is very young."),
    ("alt", "adjective", "old", "Ein altes Buch.", "An old book."),
    ("neu", "adjective", "new", "Ich habe einen neuen Job.", "I have a new job."),
    ("erste", "adjective", "first", "Es ist sein erstes Mal.", "It's his first time."),
    ("letzte", "adjective", "last", "Die letzte Chance.", "The last chance."),
    ("andere", "adjective", "other", "Ein anderer Tag.", "Another day."),
    ("gleich", "adjective", "same, equal", "Das gleiche Problem.", "The same problem."),
    ("wichtig", "adjective", "important", "Es ist wichtig für mich.", "It's important to me."),
    ("möglich", "adjective", "possible", "Das ist nicht möglich.", "That's not possible."),
    ("leicht", "adjective", "easy, light", "Es ist leicht.", "It's easy."),
    ("schwer", "adjective", "hard, heavy", "Es ist schwer zu verstehen.", "It's hard to understand."),
    ("glücklich", "adjective", "happy", "Ich bin glücklich.", "I'm happy."),
    ("traurig", "adjective", "sad", "Warum bist du traurig?", "Why are you sad?"),
    ("müde", "adjective", "tired", "Ich bin müde.", "I'm tired."),
    ("allein", "adjective", "alone", "Ich bin allein hier.", "I'm alone here."),
    ("voll", "adjective", "full", "Das Glas ist voll.", "The glass is full."),
    ("leer", "adjective", "empty", "Der Raum ist leer.", "The room is empty."),
    ("heiß", "adjective", "hot", "Der Kaffee ist heiß.", "The coffee is hot."),
    ("kalt", "adjective", "cold", "Es ist kalt draußen.", "It's cold outside."),
    ("schnell", "adjective", "fast", "Ein schnelles Auto.", "A fast car."),
    ("langsam", "adjective", "slow", "Ein langsamer Zug.", "A slow train."),

    # Adverbs / function words
    ("ja", "adverb", "yes", "Ja, natürlich.", "Yes, of course."),
    ("nein", "adverb", "no", "Nein, danke.", "No, thank you."),
    ("vielleicht", "adverb", "maybe", "Vielleicht morgen.", "Maybe tomorrow."),
    ("gut", "adverb", "well", "Mir geht es gut.", "I'm doing well."),
    ("sehr", "adverb", "very", "Sehr gut.", "Very good."),
    ("viel", "adverb", "much, a lot", "Vielen Dank.", "Thank you very much."),
    ("wenig", "adverb", "little, few", "Ich esse wenig.", "I eat little."),
    ("zu", "adverb", "too (excess)", "Es ist zu teuer.", "It's too expensive."),
    ("noch", "adverb", "still, yet", "Noch ein Mal.", "Once again."),
    ("schon", "adverb", "already", "Es ist schon erledigt.", "It's already done."),
    ("immer", "adverb", "always", "Immer zu spät.", "Always late."),
    ("nie", "adverb", "never", "Ich rauche nie.", "I never smoke."),
    ("oft", "adverb", "often", "Ich komme oft her.", "I often come here."),
    ("hier", "adverb", "here", "Komm her.", "Come here."),
    ("dort", "adverb", "there", "Er ist dort.", "He is there."),
    ("da", "adverb", "there, here", "Ich bin da.", "I'm here."),
    ("jetzt", "adverb", "now", "Nicht jetzt.", "Not now."),
    ("heute", "adverb", "today", "Heute regnet es.", "Today it's raining."),
    ("gestern", "adverb", "yesterday", "Gestern habe ich gearbeitet.", "Yesterday I worked."),
    ("morgen", "adverb", "tomorrow", "Bis morgen.", "See you tomorrow."),
    ("bald", "adverb", "soon", "Bis bald.", "See you soon."),
    ("dann", "adverb", "then", "Dann sehen wir uns.", "Then we'll see each other."),

    # Question words
    ("wo", "adverb", "where", "Wo gehst du hin?", "Where are you going?"),
    ("wann", "adverb", "when", "Wann kommst du?", "When are you coming?"),
    ("wie", "adverb", "how", "Wie geht es dir?", "How are you?"),
    ("warum", "adverb", "why", "Warum nicht?", "Why not?"),
    ("was", "pronoun", "what", "Was machst du?", "What are you doing?"),
    ("wer", "pronoun", "who", "Wer ist das?", "Who is that?"),
]


TOPIC_DECKS = {
    "travel": {
        "lemmas": ["reisen", "Auto", "Stadt", "Land", "Straße", "fahren", "ankommen"],
        "new_entries": [
            ("Reise", "noun (die)", "trip, journey", "Gute Reise!", "Have a good trip!"),
            ("Flughafen", "noun (der)", "airport", "Der Flughafen ist weit weg.", "The airport is far."),
            ("Flugzeug", "noun (das)", "airplane", "Ich nehme morgen das Flugzeug.", "I'm taking the plane tomorrow."),
            ("Zug", "noun (der)", "train", "Der Zug hat Verspätung.", "The train is delayed."),
            ("Bahnhof", "noun (der)", "train station", "Wir treffen uns am Bahnhof.", "Let's meet at the station."),
            ("Hotel", "noun (das)", "hotel", "Das Hotel ist ausgebucht.", "The hotel is fully booked."),
            ("Ticket", "noun (das)", "ticket", "Ich kaufe ein Ticket.", "I'm buying a ticket."),
            ("Koffer", "noun (der)", "suitcase", "Mein Koffer ist schwer.", "My suitcase is heavy."),
            ("Pass", "noun (der)", "passport", "Zeig deinen Pass.", "Show your passport."),
            ("Bus", "noun (der)", "bus", "Ich nehme den Bus.", "I take the bus."),
            ("Taxi", "noun (das)", "taxi", "Ruf ein Taxi.", "Call a taxi."),
            ("Strand", "noun (der)", "beach", "Der Strand ist schön.", "The beach is beautiful."),
            ("Berg", "noun (der)", "mountain", "Wir gehen in die Berge.", "We're going to the mountains."),
            ("Urlaub", "noun (der)", "vacation", "Schönen Urlaub!", "Have a good vacation!"),
            ("Karte", "noun (die)", "map, card", "Schau auf die Karte.", "Look at the map."),
            ("Grenze", "noun (die)", "border", "Wir überqueren die Grenze.", "We're crossing the border."),
            ("Ausland", "noun (das)", "abroad, foreign country", "Ich lebe im Ausland.", "I live abroad."),
        ],
    },
    "food": {
        "lemmas": ["essen", "trinken", "Brot", "Kaffee", "Wasser", "kochen"],
        "new_entries": [
            ("Essen", "noun (das)", "food, meal", "Das Essen ist lecker.", "The food is delicious."),
            ("Mahlzeit", "noun (die)", "meal", "Die Mahlzeit ist fertig.", "The meal is ready."),
            ("Frühstück", "noun (das)", "breakfast", "Ich frühstücke um sieben.", "I have breakfast at seven."),
            ("Mittagessen", "noun (das)", "lunch", "Wann ist Mittagessen?", "When is lunch?"),
            ("Abendessen", "noun (das)", "dinner", "Das Abendessen ist serviert.", "Dinner is served."),
            ("Wein", "noun (der)", "wine", "Ein Glas Rotwein.", "A glass of red wine."),
            ("Bier", "noun (das)", "beer", "Ein Bier, bitte.", "A beer, please."),
            ("Milch", "noun (die)", "milk", "Milch in den Kaffee.", "Milk in the coffee."),
            ("Käse", "noun (der)", "cheese", "Ich liebe deutschen Käse.", "I love German cheese."),
            ("Fleisch", "noun (das)", "meat", "Ich esse kein Fleisch.", "I don't eat meat."),
            ("Fisch", "noun (der)", "fish", "Der Fisch ist frisch.", "The fish is fresh."),
            ("Gemüse", "noun (das)", "vegetable", "Iss dein Gemüse.", "Eat your vegetables."),
            ("Obst", "noun (das)", "fruit", "Ich liebe Obst.", "I love fruit."),
            ("Apfel", "noun (der)", "apple", "Ein Apfel am Tag.", "An apple a day."),
            ("Ei", "noun (das)", "egg", "Zwei Spiegeleier.", "Two fried eggs."),
            ("Zucker", "noun (der)", "sugar", "Zucker im Tee.", "Sugar in the tea."),
            ("Salz", "noun (das)", "salt", "Gib mir das Salz.", "Pass me the salt."),
            ("Restaurant", "noun (das)", "restaurant", "Gehen wir ins Restaurant.", "Let's go to the restaurant."),
            ("Speisekarte", "noun (die)", "menu", "Die Speisekarte, bitte.", "The menu, please."),
            ("Rechnung", "noun (die)", "bill, invoice", "Die Rechnung, bitte.", "The bill, please."),
            ("lecker", "adjective", "delicious", "Das ist lecker!", "That's delicious!"),
        ],
    },
    "work": {
        "lemmas": ["arbeiten", "Arbeit", "Büro"],
        "new_entries": [
            ("Besprechung", "noun (die)", "meeting", "Die Besprechung beginnt um zehn.", "The meeting starts at ten."),
            ("Projekt", "noun (das)", "project", "Mein Projekt ist fertig.", "My project is finished."),
            ("Kollege", "noun (der)", "colleague", "Meine Kollegen sind nett.", "My colleagues are nice."),
            ("Chef", "noun (der)", "boss", "Der Chef kommt morgen.", "The boss arrives tomorrow."),
            ("Firma", "noun (die)", "company", "Ich mag meine Firma.", "I like my company."),
            ("Computer", "noun (der)", "computer", "Mein Computer geht nicht.", "My computer isn't working."),
            ("Telefon", "noun (das)", "phone", "Mein Telefon klingelt.", "My phone is ringing."),
            ("E-Mail", "noun (die)", "email", "Ich habe eine E-Mail geschickt.", "I sent an email."),
            ("Gehalt", "noun (das)", "salary", "Mein Gehalt ist gut.", "My salary is good."),
            ("Kunde", "noun (der)", "client, customer", "Der Kunde wartet.", "The client is waiting."),
            ("Team", "noun (das)", "team", "Mein Team ist stark.", "My team is strong."),
            ("Idee", "noun (die)", "idea", "Ich habe eine gute Idee.", "I have a good idea."),
            ("Beruf", "noun (der)", "profession", "Was ist dein Beruf?", "What's your profession?"),
        ],
    },
    "family": {
        "lemmas": ["Familie", "Vater", "Mutter", "Bruder", "Schwester", "Sohn", "Tochter", "Kind", "Freund", "Freundin", "Mann", "Frau", "Person", "Leute", "Junge", "Mädchen"],
        "new_entries": [
            ("Großvater", "noun (der)", "grandfather", "Mein Großvater erzählt Geschichten.", "My grandfather tells stories."),
            ("Großmutter", "noun (die)", "grandmother", "Meine Großmutter backt Kuchen.", "My grandmother bakes cakes."),
            ("Opa", "noun (der)", "grandpa", "Opa kommt zu Besuch.", "Grandpa is coming to visit."),
            ("Oma", "noun (die)", "grandma", "Oma macht den besten Kuchen.", "Grandma makes the best cake."),
            ("Onkel", "noun (der)", "uncle", "Mein Onkel ist nett.", "My uncle is kind."),
            ("Tante", "noun (die)", "aunt", "Meine Tante lebt in Hamburg.", "My aunt lives in Hamburg."),
            ("Cousin", "noun (der)", "cousin (male)", "Mein Cousin ist in meinem Alter.", "My cousin is my age."),
            ("Cousine", "noun (die)", "cousin (female)", "Meine Cousine ist Studentin.", "My cousin is a student."),
            ("Ehemann", "noun (der)", "husband", "Mein Ehemann arbeitet viel.", "My husband works a lot."),
            ("Ehefrau", "noun (die)", "wife", "Meine Ehefrau ist Ärztin.", "My wife is a doctor."),
            ("Nachbar", "noun (der)", "neighbor", "Mein Nachbar ist freundlich.", "My neighbor is friendly."),
            ("Eltern", "noun (pl.)", "parents", "Meine Eltern wohnen hier.", "My parents live here."),
            ("Baby", "noun (das)", "baby", "Das Baby schläft.", "The baby is sleeping."),
        ],
    },
    "home": {
        "lemmas": ["Haus", "Straße"],
        "new_entries": [
            ("Zimmer", "noun (das)", "room", "Mein Zimmer ist klein.", "My room is small."),
            ("Schlafzimmer", "noun (das)", "bedroom", "Das Schlafzimmer ist oben.", "The bedroom is upstairs."),
            ("Küche", "noun (die)", "kitchen", "Die Küche ist hinten.", "The kitchen is at the back."),
            ("Wohnzimmer", "noun (das)", "living room", "Wir sitzen im Wohnzimmer.", "We're sitting in the living room."),
            ("Badezimmer", "noun (das)", "bathroom", "Das Badezimmer ist frei.", "The bathroom is free."),
            ("Tür", "noun (die)", "door", "Schließ die Tür.", "Close the door."),
            ("Fenster", "noun (das)", "window", "Öffne das Fenster.", "Open the window."),
            ("Tisch", "noun (der)", "table", "Deck den Tisch.", "Set the table."),
            ("Stuhl", "noun (der)", "chair", "Setz dich auf den Stuhl.", "Sit on the chair."),
            ("Bett", "noun (das)", "bed", "Geh ins Bett.", "Go to bed."),
            ("Schlüssel", "noun (der)", "key", "Ich habe meine Schlüssel verloren.", "I lost my keys."),
            ("Licht", "noun (das)", "light", "Mach das Licht an.", "Turn on the light."),
            ("Wand", "noun (die)", "wall", "Die Wand ist weiß.", "The wall is white."),
            ("Dach", "noun (das)", "roof", "Eine Katze auf dem Dach.", "A cat on the roof."),
            ("Garten", "noun (der)", "garden", "Wir essen im Garten.", "We eat in the garden."),
            ("Wohnung", "noun (die)", "apartment", "Meine Wohnung ist im zweiten Stock.", "My apartment is on the second floor."),
            ("Treppe", "noun (die)", "stairs", "Geh die Treppe hoch.", "Go up the stairs."),
        ],
    },
    "body_health": {
        "lemmas": ["Hand", "Auge", "schlafen"],
        "new_entries": [
            ("Kopf", "noun (der)", "head", "Ich habe Kopfschmerzen.", "I have a headache."),
            ("Haar", "noun (das)", "hair", "Sie hat lange Haare.", "She has long hair."),
            ("Gesicht", "noun (das)", "face", "Wasch dein Gesicht.", "Wash your face."),
            ("Mund", "noun (der)", "mouth", "Öffne den Mund.", "Open your mouth."),
            ("Nase", "noun (die)", "nose", "Meine Nase ist zu.", "My nose is blocked."),
            ("Ohr", "noun (das)", "ear", "Mein Ohr tut weh.", "My ear hurts."),
            ("Zahn", "noun (der)", "tooth", "Putz die Zähne.", "Brush your teeth."),
            ("Arm", "noun (der)", "arm", "Heb den Arm.", "Raise your arm."),
            ("Bein", "noun (das)", "leg", "Mein Bein tut weh.", "My leg hurts."),
            ("Fuß", "noun (der)", "foot", "Zu Fuß ist schneller.", "On foot is faster."),
            ("Herz", "noun (das)", "heart", "Mein Herz schlägt schnell.", "My heart is beating fast."),
            ("Bauch", "noun (der)", "stomach, belly", "Mein Bauch tut weh.", "My stomach hurts."),
            ("krank", "adjective", "sick", "Ich bin heute krank.", "I'm sick today."),
            ("gesund", "adjective", "healthy", "Ich bin wieder gesund.", "I'm healthy again."),
            ("Gesundheit", "noun (die)", "health", "Gesundheit ist alles.", "Health is everything."),
            ("Arzt", "noun (der)", "doctor", "Der Arzt ist gekommen.", "The doctor has come."),
            ("Krankenhaus", "noun (das)", "hospital", "Er ist im Krankenhaus.", "He's in the hospital."),
            ("Medikament", "noun (das)", "medicine", "Nimm dieses Medikament.", "Take this medicine."),
            ("Schmerz", "noun (der)", "pain", "Der Schmerz lässt nach.", "The pain is going down."),
        ],
    },
    "time_numbers": {
        "lemmas": ["Tag", "Nacht", "Morgen", "Abend", "Woche", "Monat", "Jahr", "Stunde", "Minute", "Moment", "Zeit", "Mal", "heute", "gestern", "morgen", "jetzt"],
        "new_entries": [
            ("Sekunde", "noun (die)", "second", "Warte eine Sekunde.", "Wait a second."),
            ("Montag", "noun (der)", "Monday", "Am Montag arbeite ich.", "On Monday I work."),
            ("Dienstag", "noun (der)", "Tuesday", "Nächsten Dienstag.", "Next Tuesday."),
            ("Mittwoch", "noun (der)", "Wednesday", "Wir sehen uns am Mittwoch.", "Let's meet Wednesday."),
            ("Donnerstag", "noun (der)", "Thursday", "Donnerstagabend.", "Thursday evening."),
            ("Freitag", "noun (der)", "Friday", "Freitag ist mein Lieblingstag.", "Friday is my favorite day."),
            ("Samstag", "noun (der)", "Saturday", "Am Samstag gehen wir aus.", "On Saturday we go out."),
            ("Sonntag", "noun (der)", "Sunday", "Am Sonntag ruhe ich mich aus.", "On Sunday I rest."),
            ("eins", "number", "one", "Eins, zwei, drei.", "One, two, three."),
            ("zwei", "number", "two", "Zwei Brüder.", "Two brothers."),
            ("drei", "number", "three", "Drei Kinder.", "Three children."),
            ("vier", "number", "four", "Vier Jahreszeiten.", "Four seasons."),
            ("fünf", "number", "five", "Fünf Euro.", "Five euros."),
            ("zehn", "number", "ten", "Zehn Minuten.", "Ten minutes."),
            ("hundert", "number", "hundred", "Hundert Jahre.", "A hundred years."),
            ("tausend", "number", "thousand", "Tausend Dank.", "A thousand thanks."),
        ],
    },
    "money_shopping": {
        "lemmas": ["zahlen", "kaufen", "verkaufen"],
        "new_entries": [
            ("Geld", "noun (das)", "money", "Ich habe kein Geld.", "I don't have money."),
            ("Euro", "noun (der)", "euro", "Zehn Euro, bitte.", "Ten euros, please."),
            ("Preis", "noun (der)", "price", "Der Preis ist fair.", "The price is fair."),
            ("Geschäft", "noun (das)", "shop, business", "Das Geschäft schließt um acht.", "The shop closes at eight."),
            ("Markt", "noun (der)", "market", "Ich gehe zum Markt.", "I'm going to the market."),
            ("Kreditkarte", "noun (die)", "credit card", "Ich zahle mit Kreditkarte.", "I pay by credit card."),
            ("Bargeld", "noun (das)", "cash", "Bar oder mit Karte?", "Cash or card?"),
            ("teuer", "adjective", "expensive", "Das ist zu teuer.", "That's too expensive."),
            ("billig", "adjective", "cheap", "Dieses Restaurant ist billig.", "This restaurant is cheap."),
            ("kostenlos", "adjective", "free of charge", "Der Eintritt ist kostenlos.", "Entry is free."),
            ("Kleidung", "noun (die)", "clothing", "Ich kaufe Kleidung.", "I'm buying clothes."),
            ("Hemd", "noun (das)", "shirt", "Ein weißes Hemd.", "A white shirt."),
            ("Schuh", "noun (der)", "shoe", "Meine Schuhe sind neu.", "My shoes are new."),
            ("Tasche", "noun (die)", "bag", "Meine Tasche ist schwer.", "My bag is heavy."),
            ("Geschenk", "noun (das)", "gift", "Ein Geschenk für dich.", "A gift for you."),
            ("Supermarkt", "noun (der)", "supermarket", "Ich gehe in den Supermarkt.", "I'm going to the supermarket."),
        ],
    },
    "feelings": {
        "lemmas": ["lieben", "glücklich", "traurig", "müde", "lachen", "weinen"],
        "new_entries": [
            ("Angst", "noun (die)", "fear", "Ich habe Angst im Dunkeln.", "I'm afraid in the dark."),
            ("Wut", "noun (die)", "anger, rage", "Er ist voller Wut.", "He's full of anger."),
            ("Freude", "noun (die)", "joy", "Was für eine Freude, dich zu sehen.", "What a joy to see you."),
            ("Liebe", "noun (die)", "love", "Liebe ist alles.", "Love is everything."),
            ("besorgt", "adjective", "worried", "Ich bin besorgt um dich.", "I'm worried about you."),
            ("ruhig", "adjective", "calm, quiet", "Bleib ruhig.", "Stay calm."),
            ("nervös", "adjective", "nervous", "Ich bin nervös vor der Prüfung.", "I'm nervous before the exam."),
            ("überrascht", "adjective", "surprised", "Ich bin sehr überrascht.", "I'm very surprised."),
            ("stolz", "adjective", "proud", "Ich bin stolz auf dich.", "I'm proud of you."),
            ("verliebt", "adjective", "in love", "Er ist verliebt.", "He is in love."),
            ("gelangweilt", "adjective", "bored", "Ich bin gelangweilt.", "I'm bored."),
            ("aufgeregt", "adjective", "excited", "Die Kinder sind aufgeregt.", "The children are excited."),
            ("zufrieden", "adjective", "satisfied", "Ich bin zufrieden.", "I'm satisfied."),
            ("lächeln", "verb", "to smile", "Lächle für das Foto.", "Smile for the photo."),
            ("wütend", "adjective", "angry", "Er ist wütend auf mich.", "He's angry at me."),
        ],
    },
    "nature_weather": {
        "lemmas": [],
        "new_entries": [
            ("Sonne", "noun (die)", "sun", "Die Sonne scheint.", "The sun is shining."),
            ("Mond", "noun (der)", "moon", "Der Mond ist voll.", "The moon is full."),
            ("Stern", "noun (der)", "star", "Die Sterne leuchten.", "The stars are shining."),
            ("Himmel", "noun (der)", "sky, heaven", "Der Himmel ist blau.", "The sky is blue."),
            ("Wolke", "noun (die)", "cloud", "Es sind Wolken am Himmel.", "There are clouds in the sky."),
            ("Regen", "noun (der)", "rain", "Der Regen fällt stark.", "The rain is falling hard."),
            ("Schnee", "noun (der)", "snow", "Der Schnee ist weiß.", "The snow is white."),
            ("Wind", "noun (der)", "wind", "Der Wind bläst.", "The wind is blowing."),
            ("Wetter", "noun (das)", "weather", "Schönes Wetter heute.", "Nice weather today."),
            ("Baum", "noun (der)", "tree", "Ein großer Baum im Garten.", "A big tree in the garden."),
            ("Blume", "noun (die)", "flower", "Blumen auf dem Tisch.", "Flowers on the table."),
            ("Fluss", "noun (der)", "river", "Der Fluss ist kalt.", "The river is cold."),
            ("Meer", "noun (das)", "sea", "Wir fahren ans Meer.", "We're going to the sea."),
            ("Wald", "noun (der)", "forest", "Wir gehen im Wald spazieren.", "We walk in the forest."),
            ("Tier", "noun (das)", "animal", "Ich liebe Tiere.", "I love animals."),
            ("Hund", "noun (der)", "dog", "Mein Hund ist lieb.", "My dog is sweet."),
            ("Katze", "noun (die)", "cat", "Die Katze schläft auf dem Sofa.", "The cat is sleeping on the sofa."),
            ("Vogel", "noun (der)", "bird", "Der Vogel singt.", "The bird is singing."),
            ("Frühling", "noun (der)", "spring", "Im Frühling blüht alles.", "In spring everything blooms."),
            ("Sommer", "noun (der)", "summer", "Der Sommer ist heiß.", "Summer is hot."),
            ("Herbst", "noun (der)", "autumn", "Im Herbst regnet es viel.", "In autumn it rains a lot."),
            ("Winter", "noun (der)", "winter", "Der Winter ist kalt.", "Winter is cold."),
        ],
    },
}


if __name__ == "__main__":
    build_dataset(
        language_code="de",
        output_filename="german_top1000.json",
        entries=ENTRIES,
        topic_decks=TOPIC_DECKS,
        generated_glob="generated_entries_de*.json",
    )
